// Generated by tools/gen_api_reference_header.py. Do not edit by hand.
// Source: docs/api_reference/{jsfx,reascript_lua,fx_chain_format}.md
// Regenerate with: python3 tools/gen_api_reference_header.py
#pragma once

#include <string>
#include <unordered_map>

namespace reaforge {
namespace host {

inline constexpr const char* kJsxRef = R"MD(# JSFX Cheatsheet

> Minimum vocabulary to write a working REAPER JSFX. The full language reference is REAPER's built-in JSFX help (F1 in the JSFX editor); this file is the LLM-grounded version that fits in a single context.

## File format

A `.jsfx` file is plain text. REAPER scans `<REAPER resource>/Effects/<dir>/*.jsfx` and `<REAPER resource>/Effects/ReaForge/*.jsfx` (the ReaForge convention). The filename (minus `.jsfx`) is the FX identifier in the FX browser.

## Block structure

Every JSFX has these blocks, in this order. All are optional except `desc:`.

```
desc: <one-line description shown in the FX browser>
// optional @init, @slider, @block, @sample, @gfx blocks
```

| Block | Frequency | Purpose |
|---|---|---|
| `desc:` | once | **Required.** The FX name/description. |
| `@init` | once, on load | Initialize state, set defaults, allocate buffers. |
| `@slider` | on slider change | Read `sliderN` values when the user moves a knob. |
| `@block` | per audio buffer | Process whole-buffer logic (e.g., set `spl0` once per block). |
| `@sample` | per audio sample | Per-sample DSP. **This is where most audio code lives.** |
| `@gfx` | on UI redraw | Custom UI (sliders, meters). |

## Sliders (the user-facing knobs)

Declare in the header (top of file) — these become the FX UI:

```
desc: Tape Saturation
slider1:0<0,100,1>Drive (%)     // int 0-100
slider2:1<0,1,0.01>Mix          // float 0-1
slider3:8000<200,20000,10>HP (Hz)
```

Syntax: `sliderN:default<min,max,step>Label (units)`. `slider1`-`slider64` are valid.

## Built-in variables

| Variable | Meaning |
|---|---|
| `spl0`, `spl1`, ... | Input sample for channels 0, 1, ... (set these to produce output) |
| `srate` | Sample rate in Hz (e.g., 48000) |
| `samplesblock` | Number of samples in the current audio block |
| `numchan` | Number of I/O channels (2 for stereo) |
| `slider1`-`slider64` | Slider values (read-only inside `@sample`) |
| `t` | Current time in seconds |

## Common DSP idioms

### Bypass (always do this)
```
@sample
(slider2 >= 1) ? (
  // user wants 100% wet: replace with processed signal only
  spl0 = processed_l;
  spl1 = processed_r;
);
```

### Soft saturation (tanh)
```
@sample
drive = slider1 * 0.01;
mix   = slider2;
dry_l = spl0;
dry_r = spl1;
spl0 = tanh(spl0 * (1 + drive * 10)) * (1 - mix) + spl0 * mix;
spl1 = tanh(spl1 * (1 + drive * 10)) * (1 - mix) + spl1 * mix;
```

### Simple lowpass (one-pole)
```
@init
lp_l = lp_r = 0;
@sample
cut = slider1;
a = exp(-2*$pi*cut/srate);
lp_l = spl0 * (1-a) + lp_l * a;
lp_r = spl1 * (1-a) + lp_r * a;
```

### Time-based delay
```
@init
delay_samples = srate * 0.25;  // 250ms
buffer_idx = 0;
@sample
buf_l[buffer_idx] = spl0;
buf_r[buffer_idx] = spl1;
delayed_l = buf_l[(buffer_idx - delay_samples) | 0];
buffer_idx = (buffer_idx + 1) % delay_samples;
spl0 = spl0 + delayed_l * 0.5;
```

## Debugging tips

- Use `slider_show`/`slider_showhide` to surface internal state.
- `convolve` works with FFT convolution; `pdhalf` is `pi/2`; `$pi` is `pi`.
- Compile errors appear in REAPER's Effects → "Show development messages" or the FX error log.
- If a slider doesn't update, check the slider syntax — typos here are the #1 source of bugs.

## Common pitfalls

1. **Forgetting `desc:`** — REAPER won't show the FX.
2. **Forgetting `@init`** — `buf_l[]` allocation crashes if read first.
3. **Slider values inside `@sample`** are valid; sliders values inside `@init` are NOT (they're the defaults).
4. **Block-vs-sample confusion** — `spl0 = ...` in `@block` is applied once; in `@sample` it's per sample.

## ReaForge-specific notes

- Save to `Effects/ReaForge/<name>.jsfx`.
- The agent generates the FULL file (header + all blocks). Don't truncate.
- The user must restart REAPER (or click FX Browser → "Scan for new plug-ins") to see new JSFX.
)MD";

inline constexpr const char* kReascriptLuaRef = R"MD(# ReaScript Lua Cheatsheet

> Minimum vocabulary to write a working REAPER ReaScript in Lua. The full API is REAPER's "ReaScript API" (search inside the Actions window); this is the LLM-grounded cheat sheet.

## File format

A `.lua` file is plain Lua. Save to `<REAPER resource>/Scripts/ReaForge/<name>.lua` (the ReaForge convention).

A ReaScript is just a Lua file with a `reaper.*` API. There is no required entry point; the script's top-level body runs when invoked.

## Invocation modes

| Mode | Setup | Use case |
|---|---|---|
| **ReaScript menu** | Just save the file. | Manual one-off actions. |
| **Action (registered)** | `save_lua` with `register_action=true`. The script's path is passed to `AddRemoveReaScript(true, 0, abs_path, true)` and gets a command ID. | Bound to a key, toolbar, or MIDI. |
| **`dofile()` from another script** | Load via `dofile("<path>")`. | Composability. |

The script runs in REAPER's process. **All `reaper.*` calls are not safe to call from any thread** — they expect the REAPER main thread.

## Common API surface

### Project / Tracks

| Call | What it does |
|---|---|
| `reaper.CountTracks(0)` | Track count (proj=0 means active project). |
| `reaper.GetTrack(0, i)` | Get track by index. |
| `reaper.GetTrackName(track, "")` | Track name; pass empty buf to learn length, then pass sized buf. |
| `reaper.GetMediaItemTrack(item)` | The track that owns a media item. |
| `reaper.GetTrackNumMediaItems(track)` | Items on a track. |
| `reaper.GetTrackGUID(track)` | Stable GUID for a track. |
| `reaper.InsertTrackAtIndex(idx, false)` | Create a new track. |

### Selected items / tracks

| Call | What it does |
|---|---|
| `reaper.CountSelectedMediaItems(0)` | Selected items count. |
| `reaper.GetSelectedMediaItem(0, i)` | i-th selected item. |
| `reaper.IsMediaItemSelected(item)` | Is this item selected? |
| `reaper.CountSelectedTracks(0)` | Selected tracks count. |
| `reaper.GetSelectedTrack(0, i)` | i-th selected track. |

### MIDI

| Call | What it does |
|---|---|
| `reaper.MIDI_GetNumEvents(item)` | Number of MIDI events. |
| `reaper.MIDI_GetNote(item, i)` | Get a note (returns ok, selected, muted, startppq, endppq, chan, pitch, vel). |
| `reaper.MIDI_SetNote(item, i, ...)` | Modify a note. |
| `reaper.MIDI_InsertNote(item, ...)` | Add a note. |
| `reaper.MIDI_Sort(item)` | Re-sort after edits. |

### Transport / Playback

| Call | What it does |
|---|---|
| `reaper.GetPlayState()` | 0=stopped, 1=playing, 2=paused, etc. |
| `reaper.GetCursorPosition()` | Edit cursor (seconds). |
| `reaper.SetEditCurPos(t, false, false)` | Move cursor. |

### Project metadata

| Call | What it does |
|---|---|
| `reaper.GetProjectName(0, "", 0)` | Project name (pass empty buf to learn length). |
| `reaper.GetProjectName(0, buf, #buf+1)` | After sizing. |

## Undo handling (REQUIRED for any mutation)

Any script that mutates REAPER state **must** bracket the mutation with `Undo_BeginBlock` / `Undo_EndBlock` so the user can Ctrl-Z it:

```lua
reaper.Undo_BeginBlock()
reaper.PreventUIRefresh(1)
-- ... do stuff ...
reaper.PreventUIRefresh(-1)
reaper.Undo_EndBlock("My script name", -1)
```

Without this, REAPER's undo will skip the changes and the user has to live with the result.

## Common pattern: double velocity of selected MIDI notes

```lua
reaper.Undo_BeginBlock()
reaper.PreventUIRefresh(1)

for i = 0, reaper.CountSelectedMediaItems(0) - 1 do
  local item = reaper.GetSelectedMediaItem(0, i)
  local take = reaper.GetActiveTake(item)
  if take and reaper.TakeIsMIDI(take) then
    for j = 0, reaper.MIDI_GetNumEvents(take) - 1 do
      local ok, sel, mut, s, e, ch, pit, vel = reaper.MIDI_GetNote(take, j)
      if ok and not mut then
        reaper.MIDI_SetNote(take, j, sel, mut, s, e, ch, pit, math.min(127, vel * 2))
      end
    end
    reaper.MIDI_Sort(take)
  end
end

reaper.PreventUIRefresh(-1)
reaper.Undo_EndBlock("Double velocity of selected MIDI notes", -1)
```

## Buffer sizing for `Get*Name` functions

Functions like `GetTrackName` and `GetProjectName` write into a buffer; you must size it correctly. The idiom is:

```lua
local function get_track_name(track)
  local _, name = reaper.GetTrackName(track, "")
  return name
end
```

The empty string trick tells REAPER "tell me how big"; the second call writes into the right-sized buffer.

## ReaForge-specific notes

- Save to `Scripts/ReaForge/<name>.lua`.
- The agent generates the FULL file (not a snippet).
- `register_action=true` is the default OFF (opt-in). The user toggles it per save.
- The agent does NOT need to call `reaper.defer()` — the script runs in REAPER's main thread.
)MD";

inline constexpr const char* kFxChainFormatRef = R"MD(# FX Chain Format (REAPER RfxChain)

## ⚠️ CRITICAL: Do NOT write RfxChain files by hand

REAPER's `.RfxChain` format is a **proprietary binary/base64 format**, NOT XML. The `<FXCHAIN>` XML format documented in earlier versions of this reference was **incorrect** and will produce files that REAPER cannot read.

**The ONLY reliable way to create an `.RfxChain` is to let REAPER generate it** via a Lua script that:

1. Creates a temporary track
2. Adds the desired FX via `TrackFX_AddByName()`
3. Sets parameters via `TrackFX_SetParam()`
4. Calls `reaper.GetTrackFXChain()` to export the binary chain
5. Writes the result to `FXChains/ReaForge/<name>.RfxChain`
6. Cleans up the temporary track

## Chain Builder Template

Use the Lua template in `fx_chain-primitives/chain-builder-template.md` as the base. The template is a Lua script that the LLM fills in with:
- `{{FX_NAMES}}` — array of FX identifiers (VST: or JS: format)
- `{{FX_PARAMS}}` — per-FX parameter table: `{[fx_index] = {[param_id] = value}}`
- `{{CHAIN_NAME}}` — output filename (without extension)

The LLM calls `reaforge_save_lua("build_{{CHAIN_NAME}}", script, register_action=false)` to save and execute the builder script once, then the chain file is ready in `FXChains/ReaForge/`.

## FX Name Resolution

REAPER identifies FX by name string. The format depends on how the plugin is registered:

| Type | Format | Example |
|---|---|---|
| VST/VST3 | `VST: Name (Vendor)` or `VST3: Name (Vendor)` | `VST: ReaDelay (Cockos)` |
| JSFX | `JS: filename` | `JS: ReaDelay` |
| Built-in Cockos | May appear as VST, JS, or built-in depending on REAPER config | `VST: ReaEQ (Cockos)` or `JS: ReaEQ` |

**Fallback strategy**: if `TrackFX_AddByName(fx_name)` returns -1, try alternate formats. The template includes this logic.

## reaper.GetTrackFXChain() availability

- **REAPER 6.x+**: available as `reaper.GetTrackFXChain(track, fx_index)`
- **REAPER 5.x and earlier**: NOT available. Fall back to manual save: user adds FX manually, right-clicks the FX chain → "Save chain as..."
)MD";

inline constexpr const char* kFxChainBuilderTemplateRef = R"MD(# FX Chain Builder — Lua Script Template

Use this template to build FX chains programmatically. The LLM replaces `{{PLACEHOLDERS}}` with the specific FX names and parameter values, then calls `reaforge_save_lua()` to save the script and optionally execute it.

## Template

```lua
-- Auto-generated FX chain builder for "{{CHAIN_NAME}}"
-- Run once: REAPER creates the .RfxChain file, then you can delete this script.

local fx_names = {{FX_NAMES}}  -- e.g.: {"VST: ReaDelay (Cockos)", "VST: ReaEQ (Cockos)"}
local fx_params = {{FX_PARAMS}}  -- e.g.: {[0] = {[0] = 0.5, [1] = 0.3}, [1] = {[0] = 1.0}}
local chain_name = "{{CHAIN_NAME}}"

-- Helper: try multiple name formats for a plugin
local function add_fx_by_name(track, names)
    for _, name in ipairs(names) do
        local idx = reaper.TrackFX_AddByName(track, name, false, 1)
        if idx >= 0 then
            reaper.ShowConsoleMsg("Added: " .. name .. "\n")
            return idx
        end
    end
    reaper.ShowConsoleMsg("FAILED to add any variant of: " .. table.concat(names, ", ") .. "\n")
    return -1
end

-- Create a temporary track
reaper.InsertTrackAtIndex(0, true)
local track = reaper.GetTrack(0, 0)

-- Add each FX
local added = {}
for i, names in ipairs(fx_names) do
    -- If names is a string, wrap it; if it's already a table of alternates, use it
    local variants = type(names) == "table" and names or {names}
    local idx = add_fx_by_name(track, variants)
    if idx >= 0 then
        table.insert(added, idx)
    end
end

-- Set parameters for each added FX
for i, idx in ipairs(added) do
    local params = fx_params[i - 1]  -- 0-indexed in Lua
    if params then
        for param_id, value in pairs(params) do
            reaper.TrackFX_SetParam(track, idx, param_id, value)
        end
    end
end

-- Export the chain using REAPER's native format
local resource_path = reaper.GetResourcePath()
local chain_path = resource_path .. "/FXChains/ReaForge/" .. chain_name .. ".RfxChain"

-- GetTrackFXChain returns (boolean, string) — the string is the binary chain
local ok, chain_data = reaper.GetTrackFXChain(track, 0)
if ok and chain_data and #chain_data > 0 then
    local f = io.open(chain_path, "wb")
    if f then
        f:write(chain_data)
        f:close()
        reaper.ShowConsoleMsg("Chain saved: " .. chain_path .. "\n")
    else
        reaper.ShowConsoleMsg("FAILED to write: " .. chain_path .. "\n")
    end
else
    reaper.ShowConsoleMsg("GetTrackFXChain failed. REAPER 6.x+ required.\n")
    reaper.ShowConsoleMsg("Manual workaround: add FX manually, right-click FX chain -> Save chain as...\n")
end

-- Clean up the temporary track
reaper.DeleteTrack(track)
```

## Placeholder Guide

| Placeholder | Type | Example |
|---|---|---|
| `{{CHAIN_NAME}}` | string | `"vocal_slap"` |
| `{{FX_NAMES}}` | Lua table of strings or tables | `{{"VST: ReaDelay (Cockos)", "VST: ReaEQ (Cockos)"}}` |
| `{{FX_PARAMS}}` | Lua table: `{[fx_index] = {[param_id] = value}}` | `{[0] = {[0] = 0.25, [1] = 0.5}}` |

**FX index is 0-based** (first FX added = index 0).  
**Param IDs**: look up each plugin's parameter list. Common Cockos params are documented in the recipes.

## Multi-format name resolution

Each entry in `fx_names` can be a **string** (single name) or a **table of strings** (alternate formats to try):

```lua
-- Single format:
{"VST: ReaDelay (Cockos)"}

-- Multiple fallbacks (first match wins):
{{"VST: ReaDelay (Cockos)", "VST3: ReaDelay (Cockos)", "JS: ReaDelay"}}
```

## Post-generation

After the script runs once:
1. The `.RfxChain` file is in `FXChains/ReaForge/<name>.RfxChain`
2. The user applies it via right-click track → "FX chain" → "Load FX chain..."
3. The builder script can be deleted (it was single-use)
4. The chain file works without the script
)MD";

inline constexpr const char* kVocalSlapRecipeRef = R"MD(# Vocal Slap FX Chain Recipe

## Ingredients

| Order | FX | Purpose |
|---|---|---|
| 1 | ReaDelay (Cockos) | Slap delay (~150ms, single tap, no feedback) |
| 2 | ReaEQ (Cockos) | High-pass filter to clean low end, slight presence boost |

## ReaDelay Parameters

```
Length (time):      150 ms    (param 0 → 0.25 on a 0–1 normalized scale)
Feedback:           -45 dB    (param 1 → 0.05, almost no feedback)
Wet:                100%      (param 2 → 1.0)
Dry:                0%        (param 3 → 0.0)
```

## ReaEQ Parameters

```
Band 1 (HPF):       enabled, freq=200 Hz, Q=0.707, gain=0   (param 0–3)
Band 2 (Bell):      freq=3.2 kHz, Q=1.0, gain=+2.5 dB      (param 4–6)
Band 3 (disabled):  —                                           
Band 4 (disabled):  —
```

## Completed Placeholders

```lua
local fx_names = {
    {{"VST: ReaDelay (Cockos)", "VST3: ReaDelay (Cockos)", "JS: ReaDelay"}},
    {{"VST: ReaEQ (Cockos)", "VST3: ReaEQ (Cockos)", "JS: ReaEQ"}}
}

local fx_params = {
    [0] = {  -- ReaDelay
        [0] = 0.25,   -- Length (150ms / 600ms max ≈ 0.25)
        [1] = 0.05,   -- Feedback (-45 dB → almost zero)
        [2] = 1.0,    -- Wet
        [3] = 0.0     -- Dry
    },
    [1] = {  -- ReaEQ
        [0] = 0.5,    -- Band 1 type (0.5 = HPF)
        [1] = 1.0,    -- Band 1 enabled
        [2] = 0.33,   -- Band 1 frequency (200 Hz / 600 Hz max ≈ 0.33)
        [3] = 0.5,    -- Band 1 Q (0.707 ≈ 0.5 on 0–1 scale)
        [4] = 0.0,    -- Band 1 gain
        [5] = 1.0,    -- Band 2 enabled
        [6] = 0.5,    -- Band 2 type (0.5 = Bell)
        [7] = 0.55,   -- Band 2 frequency (3.2 kHz / 5800 Hz max ≈ 0.55)
        [8] = 0.5,    -- Band 2 Q (1.0 ≈ 0.5)
        [9] = 0.625   -- Band 2 gain (+2.5 dB on -12 to +12 range ≈ 0.625)
    }
}

local chain_name = "vocal_slap"
```

## Parameter Scale Notes

- **ReaDelay Length**: 0.0–1.0 maps to 0–600 ms. `0.25` ≈ 150 ms.
- **ReaDelay Feedback**: 0.0–1.0 maps to -120 to 0 dB. `0.05` ≈ -45 dB.
- **ReaEQ Frequency**: 0.0–1.0 maps to 20 Hz–24 kHz (log scale). For 200 Hz on band 1 (HPF default max is ~600 Hz), use `0.33`. For 3.2 kHz on band 2 (bell default max is ~5800 Hz), use `0.55`.
- **ReaEQ Gain**: 0.0–1.0 maps to -12 to +12 dB. Center (0 dB) = 0.5. +2.5 dB = `0.5 + 2.5/24 = 0.604`.
- **ReaEQ Q**: 0.0–1.0 maps to 0.1–4.0. 0.707 ≈ `0.2`, 1.0 ≈ `0.3`.

## Manual Verification

If the script fails, the user can create this chain manually:
1. Add ReaDelay to a track → set Length=150ms, Feedback=-45dB, Wet=100%, Dry=0%
2. Add ReaEQ → Band 1: HPF 200 Hz, Band 2: Bell 3.2 kHz +2.5 dB
3. Right-click FX chain → "Save chain as..." → `FXChains/ReaForge/vocal_slap.RfxChain`

## Variations

| Variation | Change |
|---|---|
| Longer slap | Length → 200–300 ms (0.33–0.5) |
| Slap with feedback | Feedback → -20 dB (0.33) |
| Brighter vocal | ReaEQ Band 2 gain → +4 dB (0.67) |
| Add de-esser | Add ReaXComp (Cockos) as FX #3, set ratio to ∞:1, threshold to -25 dB, frequency to 6–8 kHz |
)MD";


// Lookup table for `get_api_reference(target)`. Built once on first call.
inline const std::unordered_map<std::string, std::string>& api_reference_map() {
    static const std::unordered_map<std::string, std::string> m = {
        {"jsfx",            kJsxRef},
        {"reascript_lua",            kReascriptLuaRef},
        {"fx_chain_format",            kFxChainFormatRef},
        {"fx_chain-primitives/chain-builder-template",            kFxChainBuilderTemplateRef},
        {"fx_chain-primitives/recipes/vocal-slap",            kVocalSlapRecipeRef},
    };
    return m;
}

} // namespace host
} // namespace reaforge
