// Generated by tools/gen_api_reference_header.py. Do not edit by hand.
// Source: docs/api_reference/{jsfx,reascript_lua,fx_chain_format}.md
// Regenerate with: python3 tools/gen_api_reference_header.py
#pragma once

#include <string>
#include <unordered_map>

namespace reaforge {
namespace host {

inline constexpr const char* kJsxRef = R"MD(# JSFX Cheatsheet

> Minimum vocabulary to write a working REAPER JSFX. The full language reference is REAPER's built-in JSFX help (F1 in the JSFX editor); this file is the LLM-grounded version that fits in a single context.

## File format

A `.jsfx` file is plain text. REAPER scans `<REAPER resource>/Effects/<dir>/*.jsfx` and `<REAPER resource>/Effects/ReaForge/*.jsfx` (the ReaForge convention). The filename (minus `.jsfx`) is the FX identifier in the FX browser.

## Block structure

Every JSFX has these blocks, in this order. All are optional except `desc:`.

```
desc: <one-line description shown in the FX browser>
// optional @init, @slider, @block, @sample, @gfx blocks
```

| Block | Frequency | Purpose |
|---|---|---|
| `desc:` | once | **Required.** The FX name/description. |
| `@init` | once, on load | Initialize state, set defaults, allocate buffers. |
| `@slider` | on slider change | Read `sliderN` values when the user moves a knob. |
| `@block` | per audio buffer | Process whole-buffer logic (e.g., set `spl0` once per block). |
| `@sample` | per audio sample | Per-sample DSP. **This is where most audio code lives.** |
| `@gfx` | on UI redraw | Custom UI (sliders, meters). |

## Sliders (the user-facing knobs)

Declare in the header (top of file) — these become the FX UI:

```
desc: Tape Saturation
slider1:0<0,100,1>Drive (%)     // int 0-100
slider2:1<0,1,0.01>Mix          // float 0-1
slider3:8000<200,20000,10>HP (Hz)
```

Syntax: `sliderN:default<min,max,step>Label (units)`. `slider1`-`slider64` are valid.

## Built-in variables

| Variable | Meaning |
|---|---|
| `spl0`, `spl1`, ... | Input sample for channels 0, 1, ... (set these to produce output) |
| `srate` | Sample rate in Hz (e.g., 48000) |
| `samplesblock` | Number of samples in the current audio block |
| `numchan` | Number of I/O channels (2 for stereo) |
| `slider1`-`slider64` | Slider values (read-only inside `@sample`) |
| `t` | Current time in seconds |

## Common DSP idioms

### Bypass (always do this)
```
@sample
(slider2 >= 1) ? (
  // user wants 100% wet: replace with processed signal only
  spl0 = processed_l;
  spl1 = processed_r;
);
```

### Soft saturation (tanh)
```
@sample
drive = slider1 * 0.01;
mix   = slider2;
dry_l = spl0;
dry_r = spl1;
spl0 = tanh(spl0 * (1 + drive * 10)) * (1 - mix) + spl0 * mix;
spl1 = tanh(spl1 * (1 + drive * 10)) * (1 - mix) + spl1 * mix;
```

### Simple lowpass (one-pole)
```
@init
lp_l = lp_r = 0;
@sample
cut = slider1;
a = exp(-2*$pi*cut/srate);
lp_l = spl0 * (1-a) + lp_l * a;
lp_r = spl1 * (1-a) + lp_r * a;
```

### Time-based delay
```
@init
delay_samples = srate * 0.25;  // 250ms
buffer_idx = 0;
@sample
buf_l[buffer_idx] = spl0;
buf_r[buffer_idx] = spl1;
delayed_l = buf_l[(buffer_idx - delay_samples) | 0];
buffer_idx = (buffer_idx + 1) % delay_samples;
spl0 = spl0 + delayed_l * 0.5;
```

## Debugging tips

- Use `slider_show`/`slider_showhide` to surface internal state.
- `convolve` works with FFT convolution; `pdhalf` is `pi/2`; `$pi` is `pi`.
- Compile errors appear in REAPER's Effects → "Show development messages" or the FX error log.
- If a slider doesn't update, check the slider syntax — typos here are the #1 source of bugs.

## Common pitfalls

1. **Forgetting `desc:`** — REAPER won't show the FX.
2. **Forgetting `@init`** — `buf_l[]` allocation crashes if read first.
3. **Slider values inside `@sample`** are valid; sliders values inside `@init` are NOT (they're the defaults).
4. **Block-vs-sample confusion** — `spl0 = ...` in `@block` is applied once; in `@sample` it's per sample.

## ReaForge-specific notes

- Save to `Effects/ReaForge/<name>.jsfx`.
- The agent generates the FULL file (header + all blocks). Don't truncate.
- The user must restart REAPER (or click FX Browser → "Scan for new plug-ins") to see new JSFX.
)MD";

inline constexpr const char* kReascriptLuaRef = R"MD(# ReaScript Lua Cheatsheet

> Minimum vocabulary to write a working REAPER ReaScript in Lua. The full API is REAPER's "ReaScript API" (search inside the Actions window); this is the LLM-grounded cheat sheet.

## File format

A `.lua` file is plain Lua. Save to `<REAPER resource>/Scripts/ReaForge/<name>.lua` (the ReaForge convention).

A ReaScript is just a Lua file with a `reaper.*` API. There is no required entry point; the script's top-level body runs when invoked.

## Invocation modes

| Mode | Setup | Use case |
|---|---|---|
| **ReaScript menu** | Just save the file. | Manual one-off actions. |
| **Action (registered)** | `save_lua` with `register_action=true`. The script's path is passed to `AddRemoveReaScript(true, 0, abs_path, true)` and gets a command ID. | Bound to a key, toolbar, or MIDI. |
| **`dofile()` from another script** | Load via `dofile("<path>")`. | Composability. |

The script runs in REAPER's process. **All `reaper.*` calls are not safe to call from any thread** — they expect the REAPER main thread.

## Common API surface

### Project / Tracks

| Call | What it does |
|---|---|
| `reaper.CountTracks(0)` | Track count (proj=0 means active project). |
| `reaper.GetTrack(0, i)` | Get track by index. |
| `reaper.GetTrackName(track, "")` | Track name; pass empty buf to learn length, then pass sized buf. |
| `reaper.GetMediaItemTrack(item)` | The track that owns a media item. |
| `reaper.GetTrackNumMediaItems(track)` | Items on a track. |
| `reaper.GetTrackGUID(track)` | Stable GUID for a track. |
| `reaper.InsertTrackAtIndex(idx, false)` | Create a new track. |

### Selected items / tracks

| Call | What it does |
|---|---|
| `reaper.CountSelectedMediaItems(0)` | Selected items count. |
| `reaper.GetSelectedMediaItem(0, i)` | i-th selected item. |
| `reaper.IsMediaItemSelected(item)` | Is this item selected? |
| `reaper.CountSelectedTracks(0)` | Selected tracks count. |
| `reaper.GetSelectedTrack(0, i)` | i-th selected track. |

### MIDI

| Call | What it does |
|---|---|
| `reaper.MIDI_GetNumEvents(item)` | Number of MIDI events. |
| `reaper.MIDI_GetNote(item, i)` | Get a note (returns ok, selected, muted, startppq, endppq, chan, pitch, vel). |
| `reaper.MIDI_SetNote(item, i, ...)` | Modify a note. |
| `reaper.MIDI_InsertNote(item, ...)` | Add a note. |
| `reaper.MIDI_Sort(item)` | Re-sort after edits. |

### Transport / Playback

| Call | What it does |
|---|---|
| `reaper.GetPlayState()` | 0=stopped, 1=playing, 2=paused, etc. |
| `reaper.GetCursorPosition()` | Edit cursor (seconds). |
| `reaper.SetEditCurPos(t, false, false)` | Move cursor. |

### Project metadata

| Call | What it does |
|---|---|
| `reaper.GetProjectName(0, "", 0)` | Project name (pass empty buf to learn length). |
| `reaper.GetProjectName(0, buf, #buf+1)` | After sizing. |

## Undo handling (REQUIRED for any mutation)

Any script that mutates REAPER state **must** bracket the mutation with `Undo_BeginBlock` / `Undo_EndBlock` so the user can Ctrl-Z it:

```lua
reaper.Undo_BeginBlock()
reaper.PreventUIRefresh(1)
-- ... do stuff ...
reaper.PreventUIRefresh(-1)
reaper.Undo_EndBlock("My script name", -1)
```

Without this, REAPER's undo will skip the changes and the user has to live with the result.

## Common pattern: double velocity of selected MIDI notes

```lua
reaper.Undo_BeginBlock()
reaper.PreventUIRefresh(1)

for i = 0, reaper.CountSelectedMediaItems(0) - 1 do
  local item = reaper.GetSelectedMediaItem(0, i)
  local take = reaper.GetActiveTake(item)
  if take and reaper.TakeIsMIDI(take) then
    for j = 0, reaper.MIDI_GetNumEvents(take) - 1 do
      local ok, sel, mut, s, e, ch, pit, vel = reaper.MIDI_GetNote(take, j)
      if ok and not mut then
        reaper.MIDI_SetNote(take, j, sel, mut, s, e, ch, pit, math.min(127, vel * 2))
      end
    end
    reaper.MIDI_Sort(take)
  end
end

reaper.PreventUIRefresh(-1)
reaper.Undo_EndBlock("Double velocity of selected MIDI notes", -1)
```

## Buffer sizing for `Get*Name` functions

Functions like `GetTrackName` and `GetProjectName` write into a buffer; you must size it correctly. The idiom is:

```lua
local function get_track_name(track)
  local _, name = reaper.GetTrackName(track, "")
  return name
end
```

The empty string trick tells REAPER "tell me how big"; the second call writes into the right-sized buffer.

## ReaForge-specific notes

- Save to `Scripts/ReaForge/<name>.lua`.
- The agent generates the FULL file (not a snippet).
- `register_action=true` is the default OFF (opt-in). The user toggles it per save.
- The agent does NOT need to call `reaper.defer()` — the script runs in REAPER's main thread.
)MD";

inline constexpr const char* kFxChainFormatRef = R"MD(# FX Chain Format (REAPER RfxChain)

## 🛑 DO NOT CALL reaforge_save_fx_chain WITH GENERATED XML

REAPER's `.RfxChain` format is a **proprietary text/binary format** that looks like:
```
BYPASS 0 0
<VST "VST: ReaEQ (Cockos)" reaeq.dll 0 "" 1919247729<...base64...> "" ...>
FXID {GUID}
WAK 0 0
```

**The XML format (`<FXCHAIN> <FX id="0" src="...">`) is NOT what REAPER reads.**
If you call `reaforge_save_fx_chain(name, xml_content)`, the file will be unreadable
by REAPER and produce "error al leer".

**The ONLY correct way to create an `.RfxChain` is to let REAPER generate it**
via the Lua chain builder template. See `fx_chain-primitives/chain-builder-template.md`.

## Correct flow

1. Call `reaforge_get_api_reference("fx_chain-primitives/chain-builder-template")` → get the Lua template
2. Fill `{{FX_NAMES}}` and `{{FX_PARAMS}}` with the desired chain
3. Call `reaforge_save_lua("build_<name>", script, register_action=true)` → saves the builder
4. User runs the action from Actions → REAPER adds FX to the track and exports the chain
5. The `.RfxChain` file appears in `FXChains/ReaForge/`

**NEVER call `reaforge_save_fx_chain(name, content)` with hand-generated or LLM-generated XML.**
That endpoint is for programmatic use only (e.g., the Lua builder template calling
`GetTrackFXChain()` programmatically).
)MD";

inline constexpr const char* kFxChainBuilderTemplateRef = R"MD(# FX Chain Builder — Lua Script Template

Builds an FX chain on the currently selected track, exports it to
`FXChains/ReaForge/<name>.RfxChain`, then unregisters itself from the
Action List. The user runs this ONCE from Actions → it does its job and
disappears.

## How it works

1. **LLM** fills `{{FX_NAMES}}` and `{{FX_PARAMS}}` with the desired chain
2. LLM calls `reaforge_save_lua("build_{{CHAIN_NAME}}", script, register_action=true)`
3. **User** opens Actions → finds `build_{{CHAIN_NAME}}` → runs it
4. Script adds FX to the **selected track**, sets params, exports the
   chain to `FXChains/ReaForge/`, and **unregisters itself**
5. Chain file is ready. Builder action is gone.

No tracks are created or deleted — the FX are applied to whatever track
the user has selected when they run the action.

## Template

```lua
-- Auto-generated FX chain builder for "{{CHAIN_NAME}}"
-- Run ONCE from Actions. Applies FX to selected track, exports chain,
-- then unregisters itself.

local fx_names = {{FX_NAMES}}
local fx_params = {{FX_PARAMS}}
local chain_name = "{{CHAIN_NAME}}"
-- REAPER resource path + folder where this script lives
local resource_path = reaper.GetResourcePath()
local script_dir = resource_path .. "/Scripts/ReaForge"
local script_filename = "build_" .. chain_name .. ".lua"
local script_full_path = script_dir .. "/" .. script_filename

-- Helper: try multiple name formats for a plugin
local function add_fx_by_name(track, names)
    local variants = type(names) == "table" and names or {names}
    for _, v_name in ipairs(variants) do
        local idx = reaper.TrackFX_AddByName(track, v_name, false, 1)
        if idx >= 0 then
            reaper.ShowConsoleMsg("Added: " .. v_name .. " (idx=" .. idx .. ")\n")
            return idx
        end
    end
    reaper.ShowConsoleMsg("FAILED: " .. table.concat(variants, ", ") .. "\n")
    return -1
end

-- Get the selected track, or create one if nothing selected
local track = reaper.GetSelectedTrack(0, 0)
if not track then
    reaper.InsertTrackAtIndex(0, true)
    track = reaper.GetTrack(0, 0)
    reaper.SetTrackSelected(track, true)
    reaper.ShowConsoleMsg("No track selected — created a new one.\n")
end

-- Add each FX
for i, names in ipairs(fx_names) do
    local idx = add_fx_by_name(track, names)
    -- Set parameters
    if idx >= 0 then
        local params = fx_params[i - 1]  -- 0-indexed
        if params then
            for param_id, value in pairs(params) do
                reaper.TrackFX_SetParam(track, idx, param_id, value)
            end
        end
    end
end

-- Export the chain
local resource_path = reaper.GetResourcePath()
local chain_dir = resource_path .. "/FXChains/ReaForge"
reaper.RecursiveCreateDirectory(chain_dir, 0)
local chain_path = chain_dir .. "/" .. chain_name .. ".RfxChain"

local ok, chain_data = reaper.GetTrackFXChain(track, 0)
if ok and chain_data and #chain_data > 0 then
    local f = io.open(chain_path, "wb")
    if f then
        f:write(chain_data)
        f:close()
        reaper.ShowConsoleMsg("Chain saved: " .. chain_path .. "\n")
    else
        reaper.ShowConsoleMsg("FAILED to write: " .. chain_path .. "\n")
    end
else
    reaper.ShowConsoleMsg("GetTrackFXChain failed (REAPER 6.x+ required).\n")
    reaper.ShowConsoleMsg("Manual: right-click FX chain -> Save chain as... -> " .. chain_path .. "\n")
end

-- Unregister this action so it disappears from the Action List
reaper.AddRemoveReaScript(false, 0, script_full_path, true)
reaper.ShowConsoleMsg("Action unregistered: " .. script_filename .. " at " .. script_full_path .. "\n")
```

## Placeholder Guide

| Placeholder | Type | Example |
|---|---|---|
| `{{CHAIN_NAME}}` | string | `"vocal_slap"` |
| `{{FX_NAMES}}` | Lua table of strings or tables | `{{"VST: ReaDelay (Cockos)", "VST: ReaEQ (Cockos)"}}` |
| `{{FX_PARAMS}}` | Lua table: `{[fx_index] = {[param_id] = value}}` | `{[0] = {[0] = 0.25}, [1] = {[0] = 0.5}}` |

## Multi-format name resolution

Each entry in `fx_names` can be a **string** or a **table of alternates**:

```lua
-- Single format:
{"VST: ReaDelay (Cockos)"}

-- Multiple fallbacks (first match wins):
{{"VST: ReaDelay (Cockos)", "VST3: ReaDelay (Cockos)", "JS: ReaDelay"}}
```
)MD";

inline constexpr const char* kVocalSlapRecipeRef = R"MD(# Vocal Slap FX Chain Recipe

## Ingredients

| Order | FX | Purpose |
|---|---|---|
| 1 | ReaDelay (Cockos) | Slap delay (~150ms, single tap) |
| 2 | ReaEQ (Cockos) | Low-pass 12kHz, high-pass 80Hz, gentle scoop at 2.5kHz |

## Completed Placeholders (for chain-builder-template)

```lua
local fx_names = {
    {{"VST: ReaDelay (Cockos)", "VST3: ReaDelay (Cockos)", "JS: ReaDelay"}},
    {{"VST: ReaEQ (Cockos)", "VST3: ReaEQ (Cockos)", "JS: ReaEQ"}}
}

local fx_params = {
    [0] = {  -- ReaDelay
        [0] = 0.25,   -- Length (150ms / 600ms max ≈ 0.25)
        [1] = 0.05,   -- Feedback (-45 dB → almost zero)
        [2] = 1.0,    -- Wet 100%
        [3] = 0.0,    -- Dry 0%
        [4] = 0.5,    -- Low-pass filter freq (12 kHz / 20 kHz max ≈ 0.5)
        [5] = 0.08,   -- High-pass filter freq (80 Hz / 1000 Hz max ≈ 0.08)
    },
    [1] = {  -- ReaEQ
        [0] = 0.5,    -- Band 1 type (0.5 = HPF)
        [1] = 1.0,    -- Band 1 enabled
        [2] = 0.08,   -- Band 1 freq (80 Hz)
        [3] = 0.5,    -- Band 1 Q (0.707 ≈ 0.5)
        [4] = 0.0,    -- Band 1 gain
        [5] = 1.0,    -- Band 2 type (0.5 = Bell)
        [6] = 1.0,    -- Band 2 enabled
        [7] = 0.45,   -- Band 2 freq (2.5 kHz ≈ 0.45 on log scale)
        [8] = 0.35,   -- Band 2 Q (1.0 ≈ 0.35)
        [9] = 0.375,  -- Band 2 gain (-3 dB on -12 to +12 range ≈ 0.375)
        [10] = 0.5 + 2.0/24,  -- Band 3 type (0.5 = Bell)
        [11] = 1.0,   -- Band 3 enabled
        [12] = 0.62,  -- Band 3 freq (4.5 kHz ≈ 0.62)
        [13] = 0.35,  -- Band 3 Q (1.0 ≈ 0.35)
        [14] = 0.417, -- Band 3 gain (-2 dB ≈ 0.417)
    }
}

local chain_name = "vocal_slap"
```

## Parameter Scale Reference

- **ReaDelay Length**: 0–1 maps to 0–600 ms. `0.25` ≈ 150 ms.
- **ReaDelay Feedback**: 0–1 maps to -120 to 0 dB. `0.05` ≈ -45 dB.
- **ReaDelay LP cutoff**: 0–1 maps to 20–20000 Hz (log). `0.5` ≈ 12 kHz.
- **ReaDelay HP cutoff**: 0–1 maps to 20–1000 Hz (log). `0.08` ≈ 80 Hz.
- **ReaEQ Frequency**: 0–1 maps to 20–24000 Hz (log). `0.45` ≈ 2.5 kHz.
- **ReaEQ Gain**: 0–1 maps to -12 to +12 dB. Center = 0.5. Formula: `0.5 + dB/24`.
- **ReaEQ Q**: 0–1 maps to 0.1–4.0. 0.707 ≈ `0.2`, 1.0 ≈ `0.35`.

## User Flow

1. LLM generates the script via `reaforge_save_lua("build_vocal_slap", script, register_action=true)`
2. User selects a vocal track in REAPER
3. User opens Actions → finds `build_vocal_slap` → runs it
4. ReaDelay + ReaEQ are added to the track, chain exported to `FXChains/ReaForge/vocal_slap.RfxChain`
5. The action unregisters itself — gone from the Action List

## Manual Verification

If the script fails, create the chain manually:
1. Add ReaDelay → set Length=150ms, Feedback=-45dB, Wet=100%, Dry=0%, LP=12kHz, HP=80Hz
2. Add ReaEQ → HPF 80Hz, Bell -3dB @2.5kHz Q=1.0, Bell -2dB @4.5kHz Q=1.0
3. Right-click FX chain → "Save chain as..." → `FXChains/ReaForge/vocal_slap.RfxChain`
)MD";


// Lookup table for `get_api_reference(target)`. Built once on first call.
inline const std::unordered_map<std::string, std::string>& api_reference_map() {
    static const std::unordered_map<std::string, std::string> m = {
        {"jsfx",            kJsxRef},
        {"reascript_lua",            kReascriptLuaRef},
        {"fx_chain_format",            kFxChainFormatRef},
        {"fx_chain-primitives/chain-builder-template",            kFxChainBuilderTemplateRef},
        {"fx_chain-primitives/recipes/vocal-slap",            kVocalSlapRecipeRef},
    };
    return m;
}

} // namespace host
} // namespace reaforge
