// Generated by tools/gen_api_reference_header.py. Do not edit by hand.
// Auto-discovers all .md files under docs/api_reference/.
// Regenerate with: python3 tools/gen_api_reference_header.py
#pragma once

#include <string>
#include <unordered_map>

namespace reaforge {
namespace host {

inline constexpr const char* k00IndexRef = R"MD(# DSP Primitives Index

## Signal Chain Order
**utilities → filters → saturation → dynamics → delays → reverb → modulation → pitch**

## Primitive Catalog

| Target Key | Category | Lines | Description |
|---|---|---|---|
| `delays/feedback-delay` | Delays | 47 | Feedback Delay |
| `delays/modulated-delay` | Delays | 43 | Modulated Delay / Flanger Base |
| `delays/ping-pong-delay` | Delays | 46 | Ping-Pong Delay |
| `dynamics/rms-compressor` | Dynamics | 46 | RMS Compressor |
| `filters/one-pole-lowpass` | Filters | 24 | One-Pole Lowpass |
| `filters/rbj-highpass` | Filters | 42 | RBJ Highpass |
| `filters/rbj-lowpass` | Filters | 44 | RBJ Lowpass |
| `modulation/chorus-flanger` | Modulation | 53 | Chorus / Flanger |
| `pitch/psola-pitch-shift` | Pitch | 56 | PSOLA Pitch Shift |
| `reverb/fdn-reverb` | Reverb | 64 | FDN Reverb |
| `saturation/asymmetric-tanh` | Saturation | 25 | Asymmetric Tanh |
| `saturation/hard-clip-knee` | Saturation | 35 | Hard Clip with Knee |
| `saturation/tanh-soft-clip` | Saturation | 21 | Tanh Soft Clip |
| `utilities/dc-blocking` | Utilities | 25 | DC Blocking |
| `utilities/denormal-prevention` | Utilities | 13 | Denormal Prevention |
| `utilities/stereo-width` | Utilities | 25 | Stereo Width |

## Compatibility Matrix

| | `feedback-del` | `modulated-de` | `ping-pong-de` | `one-pole-low` | `rbj-highpass` | `rbj-lowpass` | `asymmetric-t` | `hard-clip-kn` | `tanh-soft-cl` | `dc-blocking` | `denormal-pre` | `stereo-width` | `rms-compress` | `chorus-flang` | `psola-pitch-` | `fdn-reverb` |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| `feedback-del` | — | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | ✓✓ |
| `modulated-de` | △ | — | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | ✓✓ |
| `ping-pong-de` | ✗ | △ | — | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | ✓✓ |
| `one-pole-low` | △ | △ | △ | — | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ |
| `rbj-highpass` | △ | △ | △ | △ | — | △ | ✓✓ | ✓✓ | ✓✓ | △ | △ | △ | △ | △ | △ | △ |
| `rbj-lowpass` | △ | △ | △ | △ | △ | — | ✓✓ | ✓✓ | ✓✓ | △ | △ | △ | △ | △ | △ | ✓✓ |
| `asymmetric-t` | △ | △ | △ | △ | △ | △ | — | △ | △ | ✓ | △ | △ | △ | △ | △ | △ |
| `hard-clip-kn` | △ | △ | △ | △ | △ | △ | △ | — | △ | ✓ | △ | △ | △ | △ | △ | △ |
| `tanh-soft-cl` | △ | △ | △ | △ | △ | △ | △ | △ | — | ✓ | △ | △ | △ | △ | △ | △ |
| `dc-blocking` | △ | △ | △ | △ | △ | △ | △ | △ | △ | — | △ | △ | △ | △ | △ | △ |
| `denormal-pre` | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | — | △ | △ | △ | △ | △ |
| `stereo-width` | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | — | △ | △ | △ | △ |
| `rms-compress` | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | — | △ | △ | △ |
| `chorus-flang` | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | — | △ | ✓✓ |
| `psola-pitch-` | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | — | ✓✓ |
| `fdn-reverb` | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | △ | — |

**Legend:** — = self | ✓ = compatible | ✓✓ = strongly compatible (category-level) | ✗ = conflicts | △ = needs verification

## Mandatory Composition Rules

1. **DC blocking AFTER any saturation primitive with drive > 2.0**
2. **Denormal prevention ALWAYS include `denorm = 1e-25;` + `+=/-=` pattern**
3. **Category order: utilities → filters → saturation → dynamics → delays → reverb → modulation → pitch**
4. **EQ before saturation to shape which frequencies distort**
5. **Gain stage between primitives: output level ≈ input level**

---
Generated by `tools/gen_dsp_index.py`. Regenerate after adding or modifying primitives.)MD";

inline constexpr const char* kFxChainFormatRef = R"MD(# FX Chain (RfxChain) Format

> Minimum vocabulary to write a valid REAPER FX Chain (`.RfxChain`) file. RfxChain files are loaded via Track → FX → "Load chain" or as inserts in a track template.

## File format

Plain XML, with a `<FXCHAIN>` root. Saved as `<REAPER resource>/FXChains/ReaForge/<name>.RfxChain` (the ReaForge convention).

## Minimal template

```xml
<FXCHAIN
  WNDRECT="0 0 0 0"
  SHOW="0"
  LASTSEL="0"
  DOCKED="0"
>
<FX id="0" src="VST:ReaEQ (Cockos)" UINPUT="0">
  <NAME>ReaEQ</NAME>
  <PRESET>
    <plain>
    </plain>
  </PRESET>
  <PARAMBEGINS>
    <P name="B1 On" vt="0"/>
    <P name="B2 On" vt="0"/>
  </PARAMBEGINS>
</FX>
<FX id="1" src="VST:ReaDelay (Cockos)" UINPUT="0">
  <NAME>ReaDelay</NAME>
  <PARAMBEGINS>
    <P name="Wet" vt="0.5"/>
  </PARAMBEGINS>
</FX>
</FXCHAIN>
```

## Tag reference

| Tag | Where | Meaning |
|---|---|---|
| `<FXCHAIN>` | root | The chain itself. Attributes: `WNDRECT` (window position), `SHOW` (0/1), `LASTSEL`, `DOCKED`. |
| `<FX id="N" src="..." UINPUT="0">` | child of FXCHAIN | One effect. `id` is position in chain (0-indexed). `src` is the plugin identifier. |
| `<NAME>` | child of FX | Display name (must match plugin). |
| `<PRESET>` | child of FX | Optional preset block. `<plain>` means no preset. |
| `<PARAMBEGINS>` | child of FX | One `<P name="ParamName" vt="Value"/>` per param. Values are strings. |

## Plugin `src` formats

| Format | Example | Notes |
|---|---|---|
| `VST:Name` | `VST:ReaEQ (Cockos)` | VST2 plugins. |
| `VST3:Name` | `VST3:ReaEQ (Cockos)` | VST3 plugins. |
| `JS:Name` | `JS:ReaDelay` | Built-in JS effects. |
| `AU:Name` | `AU:AppleAUNames` | macOS only. |
| `CLAP:Name` | `CLAP:Plugin Name` | CLAP plugins. |
| `DX:Name` | `DX:DirectXPlugin` | Windows only. |

The string after the colon is the **plugin display name as REAPER sees it** — case-sensitive. Mismatches cause the chain to load with the missing FX shown as "?".

## Common built-in FX identifiers

These are the safe-to-use ones that ship with REAPER:

- `VST:ReaEQ (Cockos)`
- `VST:ReaDelay (Cockos)`
- `VST:ReaComp (Cockos)`
- `VST:ReaGate (Cockos)`
- `VST:ReaPitch (Cockos)`
- `VST:ReaVerb (Cockos)`
- `VST:ReaXcomp (Cockos)`
- `VST:ReaSynth (Cockos)`
- `VST:ReaSamplomatic (Cockos)`
- `VST:ReaVoice (Cockos)`
- `JS:Volume` / `JS:Pan`
- `JS:Gain` (utility)

For third-party plugins, use whatever REAPER shows in the FX browser.

## Parameter name rules

`<P name="..."/>` names are the **display labels** of the parameters, not internal IDs. They must match exactly. Common param names on built-in plugins:

- ReaEQ: `B1 On`, `B1 Type`, `B1 Freq`, `B1 Gain`, `B1 Q`, `B1 Bandwidth`
- ReaDelay: `Wet`, `Time`, `Length ms`, `Feedback`
- ReaComp: `Threshold`, `Ratio`, `Attack`, `Release`, `Makeup`

The numeric value of `vt` is **always a string** (use the format you'd see in the UI). For a -6 dB threshold: `<P name="Threshold" vt="-6"/>`.

## Bypassing an FX

Set `BYPASS="1"` on the `<FX>` tag.

## ReaForge-specific notes

- Save to `FXChains/ReaForge/<name>.RfxChain`.
- The file must be valid XML; an unclosed tag breaks the whole chain on load.
- The order of `<FX>` elements is the chain order — first one is top of chain.
- Adding a new chain does NOT require a REAPER rescan (unlike JSFX); the chain appears in the "FX: Load chain" menu immediately.
- For vocal slap chains, a common pattern is: ReaEQ (high-pass at 100Hz, gentle boost at 3kHz) → ReaDelay (200ms, 25% feedback, 30% wet).
)MD";

inline constexpr const char* kJsfxAlgorithmsDynamicsRmsCompressorRef = R"MD(# RMS Compressor (Dynamics)

## Code
```jsfx
desc:RMS Compressor

slider1:-12<-60,0,0.1>Threshold (dB)
slider2:4<1,20,0.1>Ratio (:1)
slider3:10<0.1,100,0.1>Attack (ms)
slider4:50<10,500,1>Release (ms)
slider5:0<-12,12,0.1>Makeup Gain (dB)
slider6:0<0,1,1{Peak,RMS}>Detection

@init
denorm = 1e-25;
// Envelope state
env_l = env_r = 0;

@slider
threshold = 10^(slider1 / 20);
ratio = slider2;
// Attack/release coefficients
attack_coef = exp(-1 / (slider3 / 1000 * srate));
release_coef = exp(-1 / (slider4 / 1000 * srate));
makeup = 10^(slider5 / 20);
rms_mode = slider6;

@sample
// Detection: peak or RMS
det_l = rms_mode ? sqrt(env_l) : abs(spl0);
det_r = rms_mode ? sqrt(env_r) : abs(spl1);

// Gain computer: if above threshold, reduce
over_l = det_l > threshold ? det_l / threshold : 1;
over_r = det_r > threshold ? det_r / threshold : 1;
// Ratio: gain_reduction = 1 - (1 - 1/ratio) * (over - 1)
gr_l = over_l > 1 ? 1 / (1 + (over_l - 1) / ratio) : 1;
gr_r = over_r > 1 ? 1 / (1 + (over_r - 1) / ratio) : 1;

// Smooth gain reduction
coef_l = gr_l < env_l ? attack_coef : release_coef;
coef_r = gr_r < env_r ? attack_coef : release_coef;
env_l = env_l * coef_l + gr_l * (1 - coef_l);
env_r = env_r * coef_r + gr_r * (1 - coef_r);

spl0 *= env_l * makeup;
spl1 *= env_r * makeup;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Threshold | -60 to 0 dB | -12 | Level above which compression starts |
| Ratio | 1:1 to 20:1 | 4:1 | Compression ratio |
| Attack | 1–100 ms | 10 | How fast compression engages |
| Release | 10–500 ms | 50 | How fast compression releases |
| Makeup Gain | -12 to +12 dB | 0 | Post-compression level |
| Detection | Peak/RMS | RMS | RMS = smoother, Peak = faster |

## Use Case
Dynamic range control. Smooth out vocal levels, add punch to drums, glue a mix bus. Feed-forward topology — detection is on the input, gain reduction on the output.

## Compatibility
- **Before**: EQ (to shape what triggers compression), saturation
- **After**: Makeup gain, limiting, EQ
- **Requires**: Envelope state, attack/release smoothing
- **Conflicts**: Cascading compressors with fast attack can pump — use serial compression intentionally

## Source
Feed-forward RMS compressor. Based on FAUST `compressor.lib` and standard dynamics processor topology. License: MIT-compatible (FAUST).

<!-- test: Sine at -6 dB. Threshold=-12 dB, Ratio=4:1. Output should show ~1.5 dB gain reduction. -->
)MD";

inline constexpr const char* kJsfxAlgorithmsModulationChorusFlangerRef = R"MD(# Chorus / Flanger (Modulation)

## Code
```jsfx
desc:Chorus / Flanger

slider1:10<2,30,0.1>Time (ms)
slider2:5<1,15,0.1>Depth (ms)
slider3:0.5<0.05,5,0.01>Rate (Hz)
slider4:2<1,4,1>Voices
slider5:0<-20,20,0.1>Wet Gain (dB)

@init
denorm = 1e-25;
max_voices = 4;
buf_len = srate * 0.05; // 50ms per voice
bufs = 0; memset(bufs, 0, buf_len * max_voices);
wpos = 0; memset(wpos, 0, max_voices);
phase = 0; memset(phase, 0, max_voices);

@slider
center_time = slider1 / 1000 * srate;
depth_time = slider2 / 1000 * srate;
rate = slider3;
voices = min(slider4, max_voices);
wet_g = 10^(slider5 / 20);

@sample
out_l = out_r = 0;
v = 0;
loop(voices,
    // Each voice has its own LFO phase offset
    phase[v] += rate / srate;
    phase[v] >= 1 ? phase[v] -= 1;
    mod = sin((phase[v] + v * 0.25) * 2 * $pi) * depth_time;
    total_time = center_time + mod;
    
    // Read from buffer
    rpos = wpos[v] - total_time;
    rpos < 0 ? rpos += buf_len;
    frac = rpos - floor(rpos); rpos_i = floor(rpos);
    rpos_next = (rpos_i + 1) % buf_len;
    del_l = bufs[rpos_i] * (1 - frac) + bufs[rpos_next] * frac;
    
    out_l += del_l;
    
    // Write to buffer
    bufs[wpos[v]] = (spl0 + spl1) * 0.5;
    wpos[v] = (wpos[v] + 1) % buf_len;
    v += 1;
);

spl0 = spl0 + out_l * wet_g / voices;
spl1 = spl1 + out_l * wet_g / voices;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Time | 2–30 ms | 10 | Center delay. <5ms = flanger, >10ms = chorus. |
| Depth | 1–15 ms | 5 | LFO modulation depth. |
| Rate | 0.05–5 Hz | 0.5 | LFO speed. |
| Voices | 1–4 | 2 | Number of modulated voices. More = thicker. |
| Wet Gain | -20 to +20 dB | 0 | Wet level (blended with dry). |

## Use Case
Chorus: thicken guitars, pads, vocals. Flanger: jet-plane swoosh, psychedelic textures. Multiple voices with phase-offset LFOs create a rich ensemble effect. Low CPU — just delays + LFOs.

## Compatibility
- **Before**: Saturation (to add harmonics before modulation), compression
- **After**: Reverb (to spatialize), EQ
- **Requires**: Per-voice buffer, per-voice LFO phase
- **Conflicts**: Multiple chorus instances at similar rates can create beat frequencies — use different rates intentionally

## Source
Multi-voice modulated delay chorus. Standard effect topology. Based on musicdsp.org chorus article and FAUST `phaflanger.lib`. License: public domain.

<!-- test: Sine at 1 kHz. Rate=0.5Hz, Depth=5ms, Voices=2. Output should show periodic pitch modulation with stereo width from voice panning. -->
)MD";

inline constexpr const char* kJsfxAlgorithmsPitchPsolaPitchShiftRef = R"MD(# PSOLA Pitch Shift (Pitch)

## Code
```jsfx
desc:PSOLA Pitch Shift

slider1:0<-12,12,1>Shift (semitones)
slider2:256<64,1024,64>Window Size
slider3:4<2,8,1>Overlap Factor
slider4:0<-20,20,0.1>Wet Gain (dB)

@init
denorm = 1e-25;
// Buffer for overlap-add
buf_max = srate * 0.5; // 500ms
buf = 0; memset(buf, 0, buf_max * 2); // stereo
wpos = 0; read_pos = 0;
// Hann window
function hann(pos, len) (0.5 - 0.5 * cos(2 * $pi * pos / (len - 1)));

@slider
ratio = 2^(slider1 / 12); // semitones to ratio
// ratio > 1 = pitch up (read faster)
// ratio < 1 = pitch down (read slower)
win_size = slider2;
hop = win_size / slider3;
wet_g = 10^(slider4 / 20);

@sample
// Write input to buffer
buf[wpos * 2] = spl0;
buf[wpos * 2 + 1] = spl1;
wpos = (wpos + 1) % buf_max;

// Compute delayed read position for pitch shift
read_target = wpos - win_size;
read_target < 0 ? read_target += buf_max;
// Advance read position by ratio (fractional)
read_pos += ratio;
read_pos >= wpos ? read_pos -= buf_max;

// Overlap-add: mix multiple windows
out_l = out_r = 0;
i = 0; pos = read_pos;
loop(floor(win_size / hop) + 1,
    pos_int = floor(pos) % buf_max;
    frac = pos - floor(pos);
    pos_next = (pos_int + 1) % buf_max;
    win_val = hann(i * hop, win_size);
    out_l += (buf[pos_int * 2] * (1 - frac) + buf[pos_next * 2] * frac) * win_val;
    out_r += (buf[pos_int * 2 + 1] * (1 - frac) + buf[pos_next * 2 + 1] * frac) * win_val;
    pos += hop;
    i += 1;
);

spl0 = spl0 + out_l * wet_g;
spl1 = spl1 + out_r * wet_g;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Shift | -12 to +12 semitones | 0 | Pitch shift amount. 0 = unchanged. |
| Window Size | 64–1024 | 256 | Analysis window. Smaller = less latency, more artifacts. |
| Overlap Factor | 2–8 | 4 | Number of overlapping windows. Higher = smoother but more CPU. |
| Wet Gain | -20 to +20 dB | 0 | Wet signal level (blended with dry). |

## Use Case
Pitch-shift vocals for harmonies, downtune guitars, create bass from guitar. PSOLA (Pitch-Synchronous Overlap-Add) is the standard time-domain pitch shifter — better quality than simple resampling, less CPU than phase vocoder.

## Compatibility
- **Before**: Compression (to smooth dynamics before pitch shift)
- **After**: EQ (to shape the shifted tone), reverb
- **Requires**: Large buffer (srate * 0.5), Hann window function
- **Conflicts**: Cascading PSOLA shifts progressively degrade quality — use a single instance per target shift

## Source
PSOLA algorithm. Based on STK `PitchShifter` and standard overlap-add time-stretching literature. Hann window from Harris' classic paper. License: MIT-compatible (STK).

<!-- test: 1 kHz sine. Shift=+12 (octave up). Output should be 2 kHz sine with Hann-windowed overlap. -->
)MD";

inline constexpr const char* kJsfxAlgorithmsReverbFdnReverbRef = R"MD(# FDN Reverb (Reverb)

## Code
```jsfx
desc:FDN Reverb

slider1:1<0.1,10,0.1>Decay (s)
slider2:0.5<0,1,0.01>Mix
slider3:0.7<0.1,1,0.01>Damping

@init
denorm = 1e-25;
// 4 delay lines with prime-number lengths for decorrelation
n_delays = 4;
del_len = srate * 0.1; // 100ms base, primes scale it
del_lens[0] = floor(del_len * 0.017);  // ~29ms
del_lens[1] = floor(del_len * 0.023);  // ~40ms
del_lens[2] = floor(del_len * 0.031);  // ~54ms
del_lens[3] = floor(del_len * 0.043);  // ~75ms
// Buffer allocation
buf_len = del_len;
bufs = 0; memset(bufs, 0, buf_len * n_delays);
wpos = 0; memset(wpos, 0, n_delays);

// Hadamard feedback matrix (4x4, scaled by 0.5)
h00 = 0.5; h01 = 0.5; h02 = 0.5; h03 = 0.5;
h10 = 0.5; h11 = -0.5; h12 = 0.5; h13 = -0.5;
h20 = 0.5; h21 = 0.5; h22 = -0.5; h23 = -0.5;
h30 = 0.5; h31 = -0.5; h32 = -0.5; h33 = 0.5;

@slider
decay_gain = exp(-3 * 0.1 / slider1); // -60dB in decay seconds
mix = slider2;
damping = slider3;

@sample
mono = (spl0 + spl1) * 0.5;
// Read from each delay line
del[0] = bufs[wpos[0]];
del[1] = bufs[buf_len + wpos[1]];
del[2] = bufs[buf_len*2 + wpos[2]];
del[3] = bufs[buf_len*3 + wpos[3]];

// Hadamard mix + input injection
f[0] = mono + (h00*del[0] + h01*del[1] + h02*del[2] + h03*del[3]) * decay_gain;
f[1] = mono + (h10*del[0] + h11*del[1] + h12*del[2] + h13*del[3]) * decay_gain;
f[2] = mono + (h20*del[0] + h21*del[1] + h22*del[2] + h23*del[3]) * decay_gain;
f[3] = mono + (h30*del[0] + h31*del[1] + h32*del[2] + h33*del[3]) * decay_gain;

// Damping (one-pole lowpass in feedback)
d[0] = d[0] * damping + f[0] * (1 - damping);
d[1] = d[1] * damping + f[1] * (1 - damping);
d[2] = d[2] * damping + f[2] * (1 - damping);
d[3] = d[3] * damping + f[3] * (1 - damping);

// Write back
bufs[wpos[0]] = d[0]; wpos[0] = (wpos[0] + 1) % del_lens[0];
bufs[buf_len + wpos[1]] = d[1]; wpos[1] = (wpos[1] + 1) % del_lens[1];
bufs[buf_len*2 + wpos[2]] = d[2]; wpos[2] = (wpos[2] + 1) % del_lens[2];
bufs[buf_len*3 + wpos[3]] = d[3]; wpos[3] = (wpos[3] + 1) % del_lens[3];

// Output: sum all delay lines for stereo
wet = (del[0] + del[1] + del[2] + del[3]) * 0.25;
spl0 = spl0 * (1 - mix) + wet * mix;
spl1 = spl1 * (1 - mix) + wet * mix;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Decay | 0.1–10 s | 1 | RT60 decay time |
| Mix | 0–1 | 0.5 | Wet/dry mix |
| Damping | 0.1–1 | 0.7 | High-frequency absorption in feedback |

## Use Case
Natural-sounding room/hall reverb. More computationally efficient than convolution. The Hadamard matrix ensures decorrelated output from each delay line. Good for vocals, drums, ambient textures.

## Compatibility
- **Before**: EQ, compression, delay
- **After**: EQ (to shape the reverb tone)
- **Requires**: 4 delay line buffers, Hadamard matrix coefficients
- **Conflicts**: Multiple FDNs in series create dense reverb — usually one is enough

## Source
Feedback Delay Network (FDN) reverb. Based on FAUST `reverb.lib` and J. O. Smith's FDN formulation. Hadamard matrix for lossless feedback mixing. License: MIT-compatible (FAUST).

<!-- test: Impulse. Decay=1s, Mix=1.0. Output should show dense reverb tail decaying over ~1 second. -->
)MD";

inline constexpr const char* kJsfxPrimitivesDelaysFeedbackDelayRef = R"MD(# Feedback Delay (Delays)

## Code
```jsfx
desc:Feedback Delay

slider1:250<1,2000,1>Time (ms)
slider2:-12<-60,0,0.1>Feedback (dB)
slider3:0<-20,20,0.1>Wet Gain (dB)
slider4:0<-20,20,0.1>Dry Gain (dB)

@init
denorm = 1e-25;
// Circular buffer
buf_len = srate * 2; // 2 seconds max
buf_l = 0; buf_r = 0;
memset(buf_l, 0, buf_len);
memset(buf_r, 0, buf_len);
wpos = 0;

@slider
// Smooth parameter changes to avoid clicks
target_dtime = slider1 / 1000 * srate;  // delay in samples
smooth = 0.001;  // smoothing coefficient for feedback
target_fb = 10^(slider2 / 20);           // feedback linear
wet_g = 10^(slider3 / 20);
dry_g = 10^(slider4 / 20);

@sample
// Read from circular buffer
rpos = wpos - target_dtime;
rpos < 0 ? rpos += buf_len;
// Linear interpolation for fractional delay
frac = rpos - floor(rpos);
rpos_i = floor(rpos);
rpos_next = (rpos_i + 1) % buf_len;
del_l = buf_l[rpos_i] * (1 - frac) + buf_l[rpos_next] * frac;
del_r = buf_r[rpos_i] * (1 - frac) + buf_r[rpos_next] * frac;

// Write input + feedback to buffer
fb_smooth = fb_smooth * (1 - smooth) + target_fb * smooth;
buf_l[wpos] = spl0 + del_l * fb_smooth;
buf_r[wpos] = spl1 + del_r * fb_smooth;
wpos = (wpos + 1) % buf_len;

// Wet/dry mix
spl0 = spl0 * dry_g + del_l * wet_g;
spl1 = spl1 * dry_g + del_r * wet_g;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Time | 1–2000 ms | 250 | Delay time. Up to 2 seconds. |
| Feedback | -60 to 0 dB | -12 | Feedback level. -60 = single repeat. 0 = infinite. |
| Wet Gain | -20 to +20 dB | 0 | Wet signal level. |
| Dry Gain | -20 to +20 dB | 0 | Dry signal level. |

## Use Case
Basic echo, slap delay, rhythmic repeats. Foundation for all delay-based effects. Combine with filters in the feedback loop for tape-style degradation.

## Compatibility
- **Before**: Saturation (to distort the repeats), filters (to shape the echo tone)
- **After**: Reverb (to add space to the repeats)
- **Requires**: Circular buffer allocation in `@init` (srate * 2 samples)
- **Conflicts**: Multiple parallel delays need separate instances or a multi-tap design

## Source
Standard circular buffer delay with linear interpolation. JSFX `memset()` for buffer init. License: public domain.

<!-- test: Impulse at 0 dB. Time=500ms, Feedback=-6dB. Output should show distinct repeats decaying ~6dB each. No clicks, no DC buildup. -->
)MD";

inline constexpr const char* kJsfxPrimitivesDelaysModulatedDelayRef = R"MD(# Modulated Delay / Flanger Base (Delays)

## Code
```jsfx
desc:Modulated Delay / Flanger Base

slider1:5<0.5,20,0.1>Time (ms)
slider2:3<0,15,0.1>Depth (ms)
slider3:0.5<0.05,5,0.01>Rate (Hz)
slider4:0<-20,20,0.1>Wet Gain (dB)

@init
denorm = 1e-25;
buf_len = srate * 0.05; // 50ms buffer
buf_l = 0; buf_r = 0; memset(buf_l, 0, buf_len); memset(buf_r, 0, buf_len);
wpos = 0; phase = 0;

@slider
center_time = slider1 / 1000 * srate;
depth_time = slider2 / 1000 * srate;
rate = slider3;
wet_g = 10^(slider4 / 20);

@sample
// LFO for delay modulation (sine)
phase += rate / srate;
phase >= 1 ? phase -= 1;
mod = sin(phase * 2 * $pi) * depth_time;
total_time = center_time + mod;

// Read from buffer (linear interpolation)
rpos = wpos - total_time; rpos < 0 ? rpos += buf_len;
frac = rpos - floor(rpos); rpos_i = floor(rpos);
rpos_next = (rpos_i + 1) % buf_len;
del_l = buf_l[rpos_i] * (1 - frac) + buf_l[rpos_next] * frac;
del_r = buf_r[rpos_i] * (1 - frac) + buf_r[rpos_next] * frac;

// Write dry signal to buffer (no feedback for flanger)
buf_l[wpos] = spl0; buf_r[wpos] = spl1;
wpos = (wpos + 1) % buf_len;

// Mix
spl0 += del_l * wet_g;
spl1 += del_r * wet_g;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Time | 0.5–20 ms | 5 | Center delay time. Lower = flanger, higher = chorus. |
| Depth | 0–15 ms | 3 | LFO modulation depth. |
| Rate | 0.05–5 Hz | 0.5 | LFO speed. |
| Wet Gain | -20 to +20 dB | 0 | Wet signal level (blended with dry). |

## Use Case
Flanger (short time, high depth), chorus (longer time, low depth), vibrato (wet only). The modulated delay is the foundation for all short-time modulation effects. Add feedback for resonant flanging.

## Compatibility
- **Before**: Saturation (to add harmonics to the modulated signal)
- **After**: Reverb (to spatialize the chorus)
- **Requires**: Small buffer (50ms), LFO phase tracking
- **Conflicts**: Multiple modulated delays at different rates can create comb filtering — use intentionally for ensemble effects

## Source
Standard modulated delay line with sinusoidal LFO. JSFX buffer + `sin()` built-in. License: public domain.

<!-- test: Sine input at 1kHz. Rate=0.5Hz, Depth=5ms. Output should show periodic pitch modulation (vibrato). -->
)MD";

inline constexpr const char* kJsfxPrimitivesDelaysPingPongDelayRef = R"MD(# Ping-Pong Delay (Delays)

## Code
```jsfx
desc:Ping-Pong Delay

slider1:300<50,1000,1>Time (ms)
slider2:-8<-60,0,0.1>Feedback (dB)
slider3:0<-20,20,0.1>Wet Gain (dB)
slider4:0<-20,20,0.1>Dry Gain (dB)

@init
denorm = 1e-25;
buf_len = srate * 1; // 1 second mono buffer
buf = 0; memset(buf, 0, buf_len);
wpos = 0;
ping = 1; // 1 = left, 0 = right

@slider
target_dtime = slider1 / 1000 * srate;
smooth = 0.001;
target_fb = 10^(slider2 / 20);
wet_g = 10^(slider3 / 20);
dry_g = 10^(slider4 / 20);

@sample
// Read delayed sample
rpos = wpos - target_dtime; rpos < 0 ? rpos += buf_len;
frac = rpos - floor(rpos); rpos_i = floor(rpos);
rpos_next = (rpos_i + 1) % buf_len;
del = buf[rpos_i] * (1 - frac) + buf[rpos_next] * frac;

// Mono input → buffer, alternating output
mono = (spl0 + spl1) * 0.5;
fb_smooth = fb_smooth * (1 - smooth) + target_fb * smooth;
buf[wpos] = mono + del * fb_smooth;
wpos = (wpos + 1) % buf_len;

// Alternate delayed output between L and R
ping ? (
    spl0 = spl0 * dry_g + del * wet_g;
    spl1 = spl1 * dry_g;
) : (
    spl0 = spl0 * dry_g;
    spl1 = spl1 * dry_g + del * wet_g;
);
ping = !ping;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Time | 50–1000 ms | 300 | Delay time. Mono buffer. |
| Feedback | -60 to 0 dB | -8 | Decay per ping-pong pair. |
| Wet Gain | -20 to +20 dB | 0 | Wet level. |
| Dry Gain | -20 to +20 dB | 0 | Dry level. |

## Use Case
Stereo ping-pong echo. Creates width and movement. Classic for guitars, vocals, synth arpeggios. The alternating L/R output gives a bouncing spatial effect.

## Compatibility
- **Before**: Filters, saturation (to shape the echo tone)
- **After**: Reverb (to smooth the stereo image)
- **Requires**: Mono buffer (ping-pong alternates, not true stereo)
- **Conflicts**: Cascade with feedback delay for multi-tap rhythmic patterns — but watch gain staging

## Source
Standard ping-pong delay. JSFX mono buffer with alternating output. License: public domain.

<!-- test: Impulse. Time=300ms, Feedback=-8dB. Output should alternate L→R→L→R with ~8dB decay per pair. -->
)MD";

inline constexpr const char* kJsfxPrimitivesFiltersOnePoleLowpassRef = R"MD(# One-Pole Lowpass (Filters)

## Code
```jsfx
desc:One-Pole Lowpass Filter

slider1:5000<20,20000,1>Frequency (Hz)

@init
denorm = 1e-25;
a0_l = a0_r = 0;

@slider
// One-pole lowpass: y[n] = a * x[n] + (1-a) * y[n-1]
// where a = 1 - exp(-2*pi*freq/srate)
a0 = 1 - exp(-2 * $pi * slider1 / srate);

@sample
// Left
spl0 = a0 * spl0 + (1 - a0) * spl0_prev;
spl0_prev = spl0;

// Right
spl1 = a0 * spl1 + (1 - a0) * spl1_prev;
spl1_prev = spl1;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Frequency | 20–20000 Hz | 5000 | Cutoff frequency. 6 dB/octave roll-off. |

## Use Case
Quick, cheap lowpass for taming high frequencies without the computational cost of a biquad. Use when you need a simple tone control or anti-aliasing before a nonlinear stage. Not suitable for precise filtering (use RBJ for that).

## Compatibility
- **Before**: Any primitive
- **After**: Any primitive — computationally cheap, safe to cascade
- **Requires**: `denorm = 1e-25;` in `@init`
- **Conflicts**: None — composable with everything

## Source
Standard one-pole IIR filter. The coefficient `a = 1 - exp(-2*pi*fc/fs)` is the canonical formula. Documented in Julius O. Smith's "Introduction to Digital Filters". License: public domain.

<!-- test: White noise. Set freq=1000 Hz. Output should show -3dB at 1000 Hz, -6dB at 2000 Hz (6dB/oct slope). -->
)MD";

inline constexpr const char* kJsfxPrimitivesFiltersRbjHighpassRef = R"MD(# RBJ Highpass (Filters)

## Code
```jsfx
desc:RBJ Highpass Filter

slider1:500<20,20000,1>Frequency (Hz)
slider2:0.707<0.1,4,0.01>Q

@init
denorm = 1e-25;
b0 = b1 = b2 = a1 = a2 = 0;
x1_l = x2_l = y1_l = y2_l = 0;
x1_r = x2_r = y1_r = y2_r = 0;

@slider
// RBJ cookbook coefficients: highpass
w0 = 2 * $pi * slider1 / srate;
alpha = sin(w0) / (2 * slider2);
cos_w0 = cos(w0);

b0 = (1 + cos_w0) / 2;
b1 = -(1 + cos_w0);
b2 = (1 + cos_w0) / 2;
a0 = 1 + alpha;
a1 = -2 * cos_w0;
a2 = 1 - alpha;

b0 /= a0; b1 /= a0; b2 /= a0;
a1 /= a0; a2 /= a0;

@sample
// Left
y0_l = b0 * spl0 + b1 * x1_l + b2 * x2_l - a1 * y1_l - a2 * y2_l;
x2_l = x1_l; x1_l = spl0;
y2_l = y1_l; y1_l = y0_l;
spl0 = y0_l;

// Right
y0_r = b0 * spl1 + b1 * x1_r + b2 * x2_r - a1 * y1_r - a2 * y2_r;
x2_r = x1_r; x1_r = spl1;
y2_r = y1_r; y1_r = y0_r;
spl1 = y0_r;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Frequency | 20–20000 Hz | 500 | Cutoff frequency. Frequencies below this are attenuated. |
| Q | 0.1–4 | 0.707 | Resonance. 0.707 = Butterworth (no peak). >1 = resonant bump at cutoff. |

## Use Case
Remove low-frequency rumble, DC offset, or mud before other processing. Highpass before saturation prevents low frequencies from dominating the distortion. Essential for vocal chains and mastering.

## Compatibility
- **Before**: DC blocking (redundant — highpass already blocks DC)
- **After**: Saturation, compression, EQ
- **Requires**: Biquad state initialization
- **Conflicts**: Cascading multiple highpass filters progressively attenuates the low end — be intentional about cutoff stacking

## Source
RBJ Audio EQ Cookbook. Transposed direct form II. JSFX built-in math. License: public domain.

<!-- test: White noise input. Sweep freq from 20 to 20000 Hz. Output should show progressive attenuation below cutoff. Q=0.707 = -3dB at cutoff. -->
)MD";

inline constexpr const char* kJsfxPrimitivesFiltersRbjLowpassRef = R"MD(# RBJ Lowpass (Filters)

## Code
```jsfx
desc:RBJ Lowpass Filter

slider1:1000<20,20000,1>Frequency (Hz)
slider2:0.707<0.1,4,0.01>Q

@init
denorm = 1e-25;
// Biquad state (transposed direct form II)
b0 = b1 = b2 = a1 = a2 = 0;
x1_l = x2_l = y1_l = y2_l = 0;
x1_r = x2_r = y1_r = y2_r = 0;

@slider
// RBJ cookbook coefficients: lowpass
w0 = 2 * $pi * slider1 / srate;
alpha = sin(w0) / (2 * slider2);
cos_w0 = cos(w0);

b0 = (1 - cos_w0) / 2;
b1 = 1 - cos_w0;
b2 = (1 - cos_w0) / 2;
a0 = 1 + alpha;
a1 = -2 * cos_w0;
a2 = 1 - alpha;

// Normalize by a0
b0 /= a0; b1 /= a0; b2 /= a0;
a1 /= a0; a2 /= a0;

@sample
// Left channel
y0_l = b0 * spl0 + b1 * x1_l + b2 * x2_l - a1 * y1_l - a2 * y2_l;
x2_l = x1_l; x1_l = spl0;
y2_l = y1_l; y1_l = y0_l;
spl0 = y0_l;

// Right channel
y0_r = b0 * spl1 + b1 * x1_r + b2 * x2_r - a1 * y1_r - a2 * y2_r;
x2_r = x1_r; x1_r = spl1;
y2_r = y1_r; y1_r = y0_r;
spl1 = y0_r;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Frequency | 20–20000 Hz | 1000 | Cutoff frequency. |
| Q | 0.1–4 | 0.707 | Resonance. 0.707 = Butterworth (flat). >1 = resonant peak. |

## Use Case
General-purpose lowpass: remove high frequencies, tame harshness, shape tone before saturation. The RBJ biquad is the standard building block for EQ — use it before saturation to control which frequencies distort.

## Compatibility
- **Before**: DC blocking, gain staging
- **After**: Any other primitive (saturation, delay, reverb)
- **Requires**: Biquad state initialization in `@init`
- **Conflicts**: Do NOT cascade multiple RBJ biquads without re-initializing state — use separate instances per band

## Source
Robert Bristow-Johnson's Audio EQ Cookbook (https://www.w3.org/TR/audio-eq-cookbook/). Transposed direct form II implementation. JSFX `$pi`, `sin()`, `cos()` are built-in. License: public domain (cookbook), MIT-compatible.

<!-- test: White noise input. Q=0.707, sweep freq from 20000 to 20 Hz. Output should show progressive high-frequency roll-off. No clicks or instability. -->
)MD";

inline constexpr const char* kJsfxPrimitivesSaturationAsymmetricTanhRef = R"MD(# Asymmetric Tanh (Saturation)

## Code
```jsfx
desc:Asymmetric Tanh Saturation

slider1:3<1,15,0.1>Drive
slider2:0.05<0,0.5,0.01>Bias (DC Offset)
slider3:0<-12,12,0.1>Output Gain (dB)

@init
denorm = 1e-25;

@slider
drive = slider1;
bias = slider2;
out_gain = 10^(slider3 / 20);

@sample
// Asymmetric tanh: bias shifts the saturation curve, introducing even harmonics.
// Compensate for the DC offset introduced by the bias so the output stays centered.
spl0 = tanh((spl0 + bias) * drive) - tanh(bias * drive);
spl1 = tanh((spl1 + bias) * drive) - tanh(bias * drive);

spl0 = spl0 * out_gain;
spl1 = spl1 * out_gain;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Drive | 1–15 | 3 | Input gain before tanh. |
| Bias | 0–0.5 | 0.05 | DC offset for asymmetry. 0 = symmetric. Higher = more even harmonics. |
| Output Gain | -12 to +12 dB | 0 | Post-saturation level. |

## Use Case
Tape emulation, transformer saturation, tube preamp coloration. The asymmetry adds even-order harmonics (musically "warm") that symmetric saturation lacks. Use the Bias slider to control how much "character" the saturation adds.

## Compatibility
- **Before**: EQ (boost the frequencies you want to saturate)
- **After**: DC blocking (asymmetry can leave residual DC), EQ (shape the harmonics)
- **Requires**: `denorm = 1e-25;` in `@init`
- **Conflicts**: Cascading multiple asymmetric stages can accumulate DC — insert a DC block between stages

## Source
Standard asymmetric distortion technique. Documented in musicdsp.org's saturation archive. JSFX `tanh()` is built-in. License: public domain.

<!-- test: Feed a 440 Hz sine at -12 dB. With bias=0.05, the positive half of the waveform should be more rounded than the negative half. Spectrum analyzer should show even harmonics (2nd, 4th) stronger than odd. -->
)MD";

inline constexpr const char* kJsfxPrimitivesSaturationHardClipKneeRef = R"MD(# Hard Clip with Knee (Saturation)

## Code
```jsfx
desc:Hard Clip with Knee

slider1:0<-24,0,0.1>Threshold (dB)
slider2:2<0.5,10,0.1>Knee Width (dB)
slider3:0<-12,12,0.1>Output Gain (dB)

@init
denorm = 1e-25;

@slider
thresh = 10^(slider1 / 20);   // Convert dB to linear threshold
knee_w = 10^(slider2 / 20);   // Knee width in linear (above threshold)
out_gain = 10^(slider3 / 20);

@sample
// Piecewise hard clip with soft knee transition.
// For |in| < thresh: pass through
// For |in| between thresh and thresh + knee_w: quadratic blend
// For |in| > thresh + knee_w: hard clip to thresh
function clip(in, th, kw) (
    abs_in = abs(in);
    abs_in <= th ? in : (
        abs_in >= th + kw ? sign(in) * th : (
            // Quadratic knee: smooth transition from linear to hard clip.
            local(x) = (abs_in - th) / kw; // 0 at thresh, 1 at thresh+knee
            sign(in) * (th + kw * (x - x*x/2))
        )
    )
);

spl0 = clip(spl0, thresh, knee_w) * out_gain;
spl1 = clip(spl1, thresh, knee_w) * out_gain;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Threshold | -24 to 0 dB | 0 | Level above which clipping begins. |
| Knee Width | 0.5–10 dB | 2 | Width of the soft knee transition. Higher = smoother clip. |
| Output Gain | -12 to +12 dB | 0 | Post-clip level. |

## Use Case
Guitar distortion, aggressive mastering clipper, brickwall limiting. The knee provides a smooth transition from clean to clipped, avoiding the harsh artifacts of a pure hard clip. Use with EQ before to shape which frequencies hit the threshold hardest.

## Compatibility
- **Before**: EQ (boost frequencies to push into clip), compression (control dynamics before clipping)
- **After**: Low-pass filter (tame the harmonics), DC blocking
- **Requires**: `denorm = 1e-25;` in `@init`
- **Conflicts**: Cascading multiple hard clips progressively flattens the waveform — usually single-stage is best

## Source
Knee-based clipping is a standard mastering/limiter technique. The quadratic knee formula is from the DAFx soft-clipper literature. JSFX `abs()` and `sign()` are built-in. License: public domain.

<!-- test: Feed a 440 Hz sine at -6 dB. With threshold=-12 dB and knee=3 dB, the waveform should show soft rounding at the peaks. With knee=0.5 dB, it should approach a hard square-ish clip. -->
)MD";

inline constexpr const char* kJsfxPrimitivesSaturationTanhSoftClipRef = R"MD(# Tanh Soft Clip (Saturation)

## Code
```jsfx
desc:Tanh Soft Clip

slider1:2<1,10,0.1>Drive
slider2:0<-12,12,0.1>Output Gain (dB)

@init
// Denormal prevention — always include this in any JSFX with floating-point DSP.
denorm = 1e-25;

@slider
drive = slider1;
out_gain = 10^(slider2 / 20);

@sample
// Apply tanh saturation with anti-denormal guard.
spl0 = tanh(spl0 * drive) * out_gain;
spl1 = tanh(spl1 * drive) * out_gain;

// Prevent denormals from accumulating in silent sections.
spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Drive | 1–10 | 2 | Input gain before tanh. Higher = more saturation. |
| Output Gain | -12 to +12 dB | 0 | Post-saturation level. Compensate for drive attenuation. |

## Use Case
Warm tube/tape saturation, subtle mastering saturation, adding harmonics to clean signals. The tanh function is smooth and never hard-clips — it asymptotically approaches ±1. Best for signals that need "glue" without harsh distortion.

## Compatibility
- **Before**: DC blocking (if input has offset), EQ (to shape the tone before saturation)
- **After**: DC blocking (tanh can introduce small DC offset at extreme drive), gain staging
- **Requires**: `denorm = 1e-25;` in `@init` to prevent denormal stalls
- **Conflicts**: None — composable with any other primitive

## Source
Standard DSP technique. `tanh()` is available in JSFX as a built-in function. Documented in the REAPER JSFX SDK (`/websites/reaper_fm_sdk_js` on context7). License: public domain.

<!-- test: Feed a 440 Hz sine at -12 dB. With drive=2, output should show visible waveform rounding. With drive=1, output should be nearly transparent. Audio: "warm, slightly compressed tone" -->
)MD";

inline constexpr const char* kJsfxPrimitivesUtilitiesDcBlockingRef = R"MD(# DC Blocking (Utilities)

## Code
```jsfx
desc:DC Blocking Filter

@init
denorm = 1e-25;
// One-pole highpass at ~5 Hz — removes DC without affecting audio.
// Coefficient: a = exp(-2*pi*5/srate)
a0 = exp(-2 * $pi * 5 / srate);
x1_l = x1_r = y1_l = y1_r = 0;

@sample
// DC blocking filter: y[n] = x[n] - x[n-1] + a0 * y[n-1]
// Left
y0_l = spl0 - x1_l + a0 * y1_l;
x1_l = spl0;
y1_l = y0_l;
spl0 = y0_l;

// Right
y0_r = spl1 - x1_r + a0 * y1_r;
x1_r = spl1;
y1_r = y0_r;
spl1 = y0_r;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
No sliders. This is a fixed 5 Hz highpass filter that removes DC offset without audibly affecting the signal.

## Use Case
**Mandatory after any saturation primitive with drive > 2.0.** Saturation (especially asymmetric) can introduce small DC offsets. If left uncorrected, DC accumulates through subsequent processing stages, causing clicks, meter inaccuracy, and reduced headroom. Place DC blocking immediately after any nonlinear stage.

## Compatibility
- **Before**: Nothing needed — it's self-contained
- **After**: Everything. DC blocking should be one of the first stages in any chain.
- **Requires**: State variables in `@init`
- **Conflicts**: None — completely transparent to audio

## Source
One-pole highpass DC blocker. Standard technique from Julius O. Smith's "Introduction to Digital Filters". License: public domain.

<!-- test: Feed a signal with +0.5 DC offset. Output should center around zero. No audible change to audio content. -->
)MD";

inline constexpr const char* kJsfxPrimitivesUtilitiesDenormalPreventionRef = R"MD(# Denormal Prevention (Utilities)

## Code
```jsfx
desc:Denormal Prevention

@init
// The standard JSFX denormal prevention pattern.
// Add this to the @init section of every JSFX that does floating-point DSP.
// Without it, very quiet signals can cause the CPU to stall on denormal
// floating-point operations, consuming 100% CPU.
denorm = 1e-25;

@sample
// After all DSP processing in @sample, add this anti-denormal guard:
spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
No sliders. This is a code pattern, not a standalone effect. Copy the `@init` and `@sample` lines into any JSFX.

## Use Case
**Include in EVERY JSFX.** Denormal numbers are extremely small floating-point values that occur when audio fades to silence and the FPU enters a slow microcode path. The `+= denorm; -= denorm` pattern adds and immediately removes an inaudible value, flushing the FPU pipeline back to normal speed. Without this, silent sections can spike CPU usage.

## Compatibility
- **Before**: Not applicable — this is infrastructure, not processing
- **After**: Not applicable
- **Requires**: `denorm = 1e-25;` in `@init`, and the `+=/-=` pattern in `@sample`
- **Conflicts**: None — safe to include everywhere. If it's already present, adding it twice is harmless.

## Source
Documented in the REAPER JSFX SDK and community wiki. Standard pattern since JSFX inception. License: public domain.

<!-- test: Not testable as a standalone effect. Verify that the CPU meter in REAPER stays low when the track is silent. -->
)MD";

inline constexpr const char* kJsfxPrimitivesUtilitiesStereoWidthRef = R"MD(# Stereo Width (Utilities)

## Code
```jsfx
desc:Stereo Width Control

slider1:100<0,200,1>Width (%)

@init
denorm = 1e-25;

@slider
// Width: 0% = mono, 100% = original, 200% = extra wide
width = slider1 / 100;

@sample
// Mid/Side processing
mid = (spl0 + spl1) * 0.5;     // Mid = mono sum
side = (spl0 - spl1) * 0.5;    // Side = stereo difference

// Adjust side level to control width
side *= width;

// Reconstruct L/R from M/S
spl0 = mid + side;
spl1 = mid - side;

spl0 += denorm; spl0 -= denorm;
spl1 += denorm; spl1 -= denorm;
```

## Parameters
| Slider | Range | Default | Description |
|---|---|---|---|
| Width | 0–200% | 100% | 0=mono, 100=original, 200=extra wide. |

## Use Case
Adjust stereo image width. Narrow a wide synth pad to sit in the mix. Widen a narrow guitar recording. Use before reverb to control how wide the reflection field spreads.

## Compatibility
- **Before**: Any processing
- **After**: Any processing — transparent
- **Requires**: Nothing special
- **Conflicts**: Width > 100% can cause phase issues on mono playback — use with caution

## Source
Mid/Side (M/S) stereo processing. Standard technique in mastering and mixing. License: public domain.

<!-- test: Stereo signal with L=+1, R=-1 (wide). Width=0% should give L=R=0 (mono sum cancels). Width=100% preserves. Width=200% exaggerates. -->
)MD";

inline constexpr const char* kJsfxRef = R"MD(# JSFX Cheatsheet

> Minimum vocabulary to write a working REAPER JSFX. The full language reference is REAPER's built-in JSFX help (F1 in the JSFX editor); this file is the LLM-grounded version that fits in a single context.

## File format

A `.jsfx` file is plain text. REAPER scans `<REAPER resource>/Effects/<dir>/*.jsfx` and `<REAPER resource>/Effects/ReaForge/*.jsfx` (the ReaForge convention). The filename (minus `.jsfx`) is the FX identifier in the FX browser.

## Block structure

Every JSFX has these blocks, in this order. All are optional except `desc:`.

```
desc: <one-line description shown in the FX browser>
// optional @init, @slider, @block, @sample, @gfx blocks
```

| Block | Frequency | Purpose |
|---|---|---|
| `desc:` | once | **Required.** The FX name/description. |
| `@init` | once, on load | Initialize state, set defaults, allocate buffers. |
| `@slider` | on slider change | Read `sliderN` values when the user moves a knob. |
| `@block` | per audio buffer | Process whole-buffer logic (e.g., set `spl0` once per block). |
| `@sample` | per audio sample | Per-sample DSP. **This is where most audio code lives.** |
| `@gfx` | on UI redraw | Custom UI (sliders, meters). |

## Sliders (the user-facing knobs)

Declare in the header (top of file) — these become the FX UI:

```
desc: Tape Saturation
slider1:0<0,100,1>Drive (%)     // int 0-100
slider2:1<0,1,0.01>Mix          // float 0-1
slider3:8000<200,20000,10>HP (Hz)
```

Syntax: `sliderN:default<min,max,step>Label (units)`. `slider1`-`slider64` are valid.

## Built-in variables

| Variable | Meaning |
|---|---|
| `spl0`, `spl1`, ... | Input sample for channels 0, 1, ... (set these to produce output) |
| `srate` | Sample rate in Hz (e.g., 48000) |
| `samplesblock` | Number of samples in the current audio block |
| `numchan` | Number of I/O channels (2 for stereo) |
| `slider1`-`slider64` | Slider values (read-only inside `@sample`) |
| `t` | Current time in seconds |

## Common DSP idioms

### Bypass (always do this)
```
@sample
(slider2 >= 1) ? (
  // user wants 100% wet: replace with processed signal only
  spl0 = processed_l;
  spl1 = processed_r;
);
```

### Soft saturation (tanh)
```
@sample
drive = slider1 * 0.01;
mix   = slider2;
dry_l = spl0;
dry_r = spl1;
spl0 = tanh(spl0 * (1 + drive * 10)) * (1 - mix) + spl0 * mix;
spl1 = tanh(spl1 * (1 + drive * 10)) * (1 - mix) + spl1 * mix;
```

### Simple lowpass (one-pole)
```
@init
lp_l = lp_r = 0;
@sample
cut = slider1;
a = exp(-2*$pi*cut/srate);
lp_l = spl0 * (1-a) + lp_l * a;
lp_r = spl1 * (1-a) + lp_r * a;
```

### Time-based delay
```
@init
delay_samples = srate * 0.25;  // 250ms
buffer_idx = 0;
@sample
buf_l[buffer_idx] = spl0;
buf_r[buffer_idx] = spl1;
delayed_l = buf_l[(buffer_idx - delay_samples) | 0];
buffer_idx = (buffer_idx + 1) % delay_samples;
spl0 = spl0 + delayed_l * 0.5;
```

## Debugging tips

- Use `slider_show`/`slider_showhide` to surface internal state.
- `convolve` works with FFT convolution; `pdhalf` is `pi/2`; `$pi` is `pi`.
- Compile errors appear in REAPER's Effects → "Show development messages" or the FX error log.
- If a slider doesn't update, check the slider syntax — typos here are the #1 source of bugs.

## Common pitfalls

1. **Forgetting `desc:`** — REAPER won't show the FX.
2. **Forgetting `@init`** — `buf_l[]` allocation crashes if read first.
3. **Slider values inside `@sample`** are valid; sliders values inside `@init` are NOT (they're the defaults).
4. **Block-vs-sample confusion** — `spl0 = ...` in `@block` is applied once; in `@sample` it's per sample.

## ReaForge-specific notes

- Save to `Effects/ReaForge/<name>.jsfx`.
- The agent generates the FULL file (header + all blocks). Don't truncate.
- The user must restart REAPER (or click FX Browser → "Scan for new plug-ins") to see new JSFX.
)MD";

inline constexpr const char* kReascriptLuaRef = R"MD(# ReaScript Lua Cheatsheet

> Minimum vocabulary to write a working REAPER ReaScript in Lua. The full API is REAPER's "ReaScript API" (search inside the Actions window); this is the LLM-grounded cheat sheet.

## File format

A `.lua` file is plain Lua. Save to `<REAPER resource>/Scripts/ReaForge/<name>.lua` (the ReaForge convention).

A ReaScript is just a Lua file with a `reaper.*` API. There is no required entry point; the script's top-level body runs when invoked.

## Invocation modes

| Mode | Setup | Use case |
|---|---|---|
| **ReaScript menu** | Just save the file. | Manual one-off actions. |
| **Action (registered)** | `save_lua` with `register_action=true`. The script's path is passed to `AddRemoveReaScript(true, 0, abs_path, true)` and gets a command ID. | Bound to a key, toolbar, or MIDI. |
| **`dofile()` from another script** | Load via `dofile("<path>")`. | Composability. |

The script runs in REAPER's process. **All `reaper.*` calls are not safe to call from any thread** — they expect the REAPER main thread.

## Common API surface

### Project / Tracks

| Call | What it does |
|---|---|
| `reaper.CountTracks(0)` | Track count (proj=0 means active project). |
| `reaper.GetTrack(0, i)` | Get track by index. |
| `reaper.GetTrackName(track, "")` | Track name; pass empty buf to learn length, then pass sized buf. |
| `reaper.GetMediaItemTrack(item)` | The track that owns a media item. |
| `reaper.GetTrackNumMediaItems(track)` | Items on a track. |
| `reaper.GetTrackGUID(track)` | Stable GUID for a track. |
| `reaper.InsertTrackAtIndex(idx, false)` | Create a new track. |

### Selected items / tracks

| Call | What it does |
|---|---|
| `reaper.CountSelectedMediaItems(0)` | Selected items count. |
| `reaper.GetSelectedMediaItem(0, i)` | i-th selected item. |
| `reaper.IsMediaItemSelected(item)` | Is this item selected? |
| `reaper.CountSelectedTracks(0)` | Selected tracks count. |
| `reaper.GetSelectedTrack(0, i)` | i-th selected track. |

### MIDI

| Call | What it does |
|---|---|
| `reaper.MIDI_GetNumEvents(item)` | Number of MIDI events. |
| `reaper.MIDI_GetNote(item, i)` | Get a note (returns ok, selected, muted, startppq, endppq, chan, pitch, vel). |
| `reaper.MIDI_SetNote(item, i, ...)` | Modify a note. |
| `reaper.MIDI_InsertNote(item, ...)` | Add a note. |
| `reaper.MIDI_Sort(item)` | Re-sort after edits. |

### Transport / Playback

| Call | What it does |
|---|---|
| `reaper.GetPlayState()` | 0=stopped, 1=playing, 2=paused, etc. |
| `reaper.GetCursorPosition()` | Edit cursor (seconds). |
| `reaper.SetEditCurPos(t, false, false)` | Move cursor. |

### Project metadata

| Call | What it does |
|---|---|
| `reaper.GetProjectName(0, "", 0)` | Project name (pass empty buf to learn length). |
| `reaper.GetProjectName(0, buf, #buf+1)` | After sizing. |

## Undo handling (REQUIRED for any mutation)

Any script that mutates REAPER state **must** bracket the mutation with `Undo_BeginBlock` / `Undo_EndBlock` so the user can Ctrl-Z it:

```lua
reaper.Undo_BeginBlock()
reaper.PreventUIRefresh(1)
-- ... do stuff ...
reaper.PreventUIRefresh(-1)
reaper.Undo_EndBlock("My script name", -1)
```

Without this, REAPER's undo will skip the changes and the user has to live with the result.

## Common pattern: double velocity of selected MIDI notes

```lua
reaper.Undo_BeginBlock()
reaper.PreventUIRefresh(1)

for i = 0, reaper.CountSelectedMediaItems(0) - 1 do
  local item = reaper.GetSelectedMediaItem(0, i)
  local take = reaper.GetActiveTake(item)
  if take and reaper.TakeIsMIDI(take) then
    for j = 0, reaper.MIDI_GetNumEvents(take) - 1 do
      local ok, sel, mut, s, e, ch, pit, vel = reaper.MIDI_GetNote(take, j)
      if ok and not mut then
        reaper.MIDI_SetNote(take, j, sel, mut, s, e, ch, pit, math.min(127, vel * 2))
      end
    end
    reaper.MIDI_Sort(take)
  end
end

reaper.PreventUIRefresh(-1)
reaper.Undo_EndBlock("Double velocity of selected MIDI notes", -1)
```

## Buffer sizing for `Get*Name` functions

Functions like `GetTrackName` and `GetProjectName` write into a buffer; you must size it correctly. The idiom is:

```lua
local function get_track_name(track)
  local _, name = reaper.GetTrackName(track, "")
  return name
end
```

The empty string trick tells REAPER "tell me how big"; the second call writes into the right-sized buffer.

## ReaForge-specific notes

- Save to `Scripts/ReaForge/<name>.lua`.
- The agent generates the FULL file (not a snippet).
- `register_action=true` is the default OFF (opt-in). The user toggles it per save.
- The agent does NOT need to call `reaper.defer()` — the script runs in REAPER's main thread.
)MD";


// Lookup table for `get_api_reference(target)`. Built once on first call.
inline const std::unordered_map<std::string, std::string>& api_reference_map() {
    static const std::unordered_map<std::string, std::string> m = {
        {"00-index",            k00IndexRef},
        {"fx_chain_format",            kFxChainFormatRef},
        {"jsfx-algorithms/dynamics/rms-compressor",            kJsfxAlgorithmsDynamicsRmsCompressorRef},
        {"jsfx-algorithms/modulation/chorus-flanger",            kJsfxAlgorithmsModulationChorusFlangerRef},
        {"jsfx-algorithms/pitch/psola-pitch-shift",            kJsfxAlgorithmsPitchPsolaPitchShiftRef},
        {"jsfx-algorithms/reverb/fdn-reverb",            kJsfxAlgorithmsReverbFdnReverbRef},
        {"jsfx-primitives/delays/feedback-delay",            kJsfxPrimitivesDelaysFeedbackDelayRef},
        {"jsfx-primitives/delays/modulated-delay",            kJsfxPrimitivesDelaysModulatedDelayRef},
        {"jsfx-primitives/delays/ping-pong-delay",            kJsfxPrimitivesDelaysPingPongDelayRef},
        {"jsfx-primitives/filters/one-pole-lowpass",            kJsfxPrimitivesFiltersOnePoleLowpassRef},
        {"jsfx-primitives/filters/rbj-highpass",            kJsfxPrimitivesFiltersRbjHighpassRef},
        {"jsfx-primitives/filters/rbj-lowpass",            kJsfxPrimitivesFiltersRbjLowpassRef},
        {"jsfx-primitives/saturation/asymmetric-tanh",            kJsfxPrimitivesSaturationAsymmetricTanhRef},
        {"jsfx-primitives/saturation/hard-clip-knee",            kJsfxPrimitivesSaturationHardClipKneeRef},
        {"jsfx-primitives/saturation/tanh-soft-clip",            kJsfxPrimitivesSaturationTanhSoftClipRef},
        {"jsfx-primitives/utilities/dc-blocking",            kJsfxPrimitivesUtilitiesDcBlockingRef},
        {"jsfx-primitives/utilities/denormal-prevention",            kJsfxPrimitivesUtilitiesDenormalPreventionRef},
        {"jsfx-primitives/utilities/stereo-width",            kJsfxPrimitivesUtilitiesStereoWidthRef},
        {"jsfx",            kJsfxRef},
        {"reascript_lua",            kReascriptLuaRef},
    };
    return m;
}

} // namespace host
} // namespace reaforge
