#!/usr/bin/env python3
"""
gen_api_reference_header.py — regenerate src/host/api_reference_data.h from
the 3 cheatsheet markdowns in docs/api_reference/.

The hand-rolled C++11 raw-string-literal approach is used (R"MD(...)MD") so
markdown content (which has backticks, asterisks, and pipes) is embedded
verbatim without escaping.

Run from the repo root:
    python3 tools/gen_api_reference_header.py

The generated header is committed to the repo. Re-run only when the
cheatsheets change.
"""
from pathlib import Path
import sys

REPO = Path(__file__).resolve().parent.parent
SOURCES = {
    "jsfx":            REPO / "docs" / "api_reference" / "jsfx.md",
    "reascript_lua":   REPO / "docs" / "api_reference" / "reascript_lua.md",
    "fx_chain_format": REPO / "docs" / "api_reference" / "fx_chain_format.md",
}
OUT = REPO / "src" / "host" / "api_reference_data.h"

CONST_NAMES = {
    "jsfx":            "kJsxRef",
    "reascript_lua":   "kReascriptLuaRef",
    "fx_chain_format": "kFxChainFormatRef",
}

HEADER = """// Generated by tools/gen_api_reference_header.py. Do not edit by hand.
// Source: docs/api_reference/{jsfx,reascript_lua,fx_chain_format}.md
// Regenerate with: python3 tools/gen_api_reference_header.py
#pragma once

#include <string>
#include <unordered_map>

namespace reaforge {
namespace host {

"""

FOOTER = """
// Lookup table for `get_api_reference(target)`. Built once on first call.
inline const std::unordered_map<std::string, std::string>& api_reference_map() {
    static const std::unordered_map<std::string, std::string> m = {
"""

FOOTER_2 = """    };
    return m;
}

} // namespace host
} // namespace reaforge
"""


def main() -> int:
    for key, path in SOURCES.items():
        if not path.exists():
            print(f"ERROR: source markdown missing: {path}", file=sys.stderr)
            return 1

    parts = [HEADER]
    for key, const_name in CONST_NAMES.items():
        content = SOURCES[key].read_text(encoding="utf-8")
        parts.append(f'inline constexpr const char* {const_name} = R"MD({content})MD";\n\n')

    parts.append(FOOTER)
    for key in SOURCES.keys():
        parts.append(f'        {{"{key}",            {CONST_NAMES[key]}}},\n')
    parts.append(FOOTER_2)

    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
